#!/bin/bash
#
# simple killer
#

. /usr/lib/vdr/easyvdr-config-loader                   ## common defines


A_R_MASTER="/etc/auto.master"
AUTOFS_SETUP_STATE="$EASYVDR_LOGDIR/autofs-setup.state"

MARK4="Installierte Partition:"


SAS="$(service autofs status)"
SAS_RUNNING=$(echo $SAS | grep -c "start/running")
(( $SAS_RUNNING != 0 )) && service autofs stop

LIST_of_LINKS=$(grep "$MARK4" "$AUTOFS_SETUP_STATE" | cut -d: -f2 | cut -d" "  -f2)

for LINK_to_KILL in "$LIST_of_LINKS"
  do
    rm -f $LINK_to_KILL
  done

[[  -e "$A_R_MASTER.backup" ]] && mv -f "$A_R_MASTER.backup" $A_R_MASTER 
rm -f -R /var/autofs/*
rm -f -R /etc/autousb
rm -f -R /etc/udev/rules.d/42-easy_usb.rules
mv -f    $AUTOFS_SETUP_STATE  $AUTOFS_SETUP_STATE.old
echo " removed links"  >>     $AUTOFS_SETUP_STATE.old
echo " $LIST_of_LINKS" >>     $AUTOFS_SETUP_STATE.old

exit 17

