.TH atsc_epg 1 "February 14, 2010"
.SH NAME
atsc_epg \- an electronic program guide using ATSC devices.
.SH SYNOPSIS
.B atsc_epg
.RI [ options ]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B atsc_epg
commands.
.PP
\fBatsc_epg\fP is an electronic program guide for ATSC devices.
.SH OPTIONS
.TP
.B \-a
adapter index to use, (default 0)
.TP
.B \-f
tuning frequency
.TP
.B \-h
print this help text
.TP
.B \-p
period in hours, (default 12)
.TP
.B \-m
modulation ATSC vsb_8|vsb_16 (default vsb_8)
.TP
.B \-t
enable ETT to receive program details, if available
.br
.PP
This manual page was written by Uwe Bugla <uwe.bugla@gmx.de>.
