.TH av7110_loadkeys 1 "February 14, 2010"
.SH NAME
av7110_loadkeys \- a program to load keymaps.
.SH SYNOPSIS
.B av7110_loadkeys
.RI [ options ] keymap_filename.(rc5|rcmm
.br
.SH DESCRIPTION
This manual page documents briefly the
.B av7110_loadkeys
commands.
.PP
\fBav7110_loadkeys\fP is a program to load keymaps.
.SH OPTIONS
.TP
.B \-i
invert
.TP
.B \-a
address <num>
.TP
.B \-h
print this help text
.br
.PP
This manual page was written by Uwe Bugla <uwe.bugla@gmx.de>.
