.TH dst_test 1 "February 14, 2010"
.SH NAME
dst_test \- a Twinhan DST and clones test utility.
.SH SYNOPSIS
.B dst_test
.RI [ options ]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B dst_test
commands.
.PP
\fBdst_test\fP is a Twinhan DST and clones test utility.
.SH OPTIONS
.TP
.B \-c
capabilities
.TP
.B \-i
info
.TP
.B \-r
reset
.TP
.B \-p
pid
.TP
.B \-g
get descr
.TP
.B \-s
set_descr
.TP
.B \-a
app_info
.TP
.B \-t
session test
.br
.PP
This manual page was written by Uwe Bugla <uwe.bugla@gmx.de>.
