.TH dvbdate 1 "February 14, 2010"
.SH NAME
dvbdate \- a program to show the actual time.
.SH SYNOPSIS
.B dvbdate
.RI [ options ]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B dvbdate
commands.
.PP
\fBdvbdate\fP is a program to show the actual time.
.SH OPTIONS
.TP
.B \-a --adapter
adapter to use, default: 0
.TP
.B \-p --print
print current time, received time and delta
.TP
.B \-s --set
set the system clock to received time
.TP
.B \-f --force
force the setting of the clock
.TP
.B \-q --quiet
be silent
.TP
.B \-h --help
display this message
.TP
.B \-t --timeout n
max seconds to wait, default: 25
.br
.PP
This manual page was written by Uwe Bugla <uwe.bugla@gmx.de>.
