.TH dvbnet 1 "February 14, 2009"
.SH NAME
dvbnet \- a DVB Network Interface Manager.
.SH SYNOPSIS
.B dvbnet
.RI [ options ]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B dvbnet
commands.
.PP
\fBdvbnet\fP is a DVB Network Interface Manager.
.SH OPTIONS
.TP
.B \-a AD
Adapter card (default 0)
.TP
.B \-n DD
Demux (default 0)
.TP
.B \-p PID
Add interface listening on PID
.TP
.B \-d NUM
Remove interface NUM
.TP
.B \-l
List currently available interfaces
.TP
.B \-U
use ULE framing (default: MPE)
.TP
.B \-v
Print current version
.br
.PP
This manual page was written by Uwe Bugla <uwe.bugla@gmx.de>.
