.TH dvbtraffic 1 "February 14, 2010"
.SH NAME
dvbtraffic \- a program to show satellite traffic.
.SH SYNOPSIS
.B dvbtraffic
.RI [ options ]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B dvbtraffic
commands.
.PP
\fBdvbtraffic\fP is a program to show satellite traffic.
.SH OPTIONS
.TP
.B \-a N
use dvb adapter N
.TP
.B \-d N
use demux N
.TP
.B \-h
display this help
.br
.PP
This manual page was written by Uwe Bugla <uwe.bugla@gmx.de>.
