--- a/Makefile
+++ b/Makefile
@@ -22,7 +22,7 @@
 
 ### Make sure that necessary options are included:
 
-include $(VDRDIR)/Make.global
+-include $(VDRDIR)/Make.global
 
 ### Allow user defined options to overwrite defaults:
 
