#! /bin/sh
# postinst script for vdr-plugin-block
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
#
# quoting from the policy:
#     Any necessary prompting should almost always be confined to the
#     post-installation script, and should be protected with a conditional
#     so that unnecessary prompting doesn't happen if a package's
#     installation fails and the `postinst' is called with `abort-upgrade',
#     `abort-remove' or `abort-deconfigure'.

# source debconf lib
. /usr/share/debconf/confmodule

case "$1" in
    configure)
        # Move old config file to new location
        cfg_dir=/var/lib/vdr/plugins
        if dpkg --compare-versions "$2" lt "0.0.3" ; then
            if [ -e $cfg_dir/taste.conf ] && [ ! -e $cfg_dir/block.conf ] ; then
                mv $cfg_dir/taste.conf $cfg_dir/block.conf
            fi
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
