#!/bin/bash
# 
#
#
#################################################


updatedb

AKT_KERNEL=$(uname -r)
L_DRIVER_DIR="/lib/modules/$AKT_KERNEL/kernel/drivers/media/rc"
L_MODULE_DIR="/lib/modules/$AKT_KERNEL/kernel/drivers/staging/media/lirc"

# "fremde" lirc_dev.ko lahmlegen 
DEV_FOUNDS=$(locate -b '\lirc_dev.ko')
for DEV_FOUND in $DEV_FOUNDS
  do
    if echo $DEV_FOUND | grep -q "/lib/modules/$AKT_KERNEL"; then
      [[ "$(dirname $DEV_FOUND)" != "$L_DRIVER_DIR" ]] && mv -f $DEV_FOUND "${DEV_FOUND/.ko}".SAV
    fi
  done

