#!/bin/bash
#
#
#  xbmc_config_audio
#  to set audio-parameter in xbmc automatically
#
#  fuer xbmc-version
#  0.0.12RC1 20.12.2012    1st try by michel8
#  0.0.12RC3 14.01.2013    cleanup $VDR => $CFG_DIR wg. config-loader  C.B.
#  0.0.12RC3 22.01.2013    tut auch wenn xbmc noch keine guisettings.xml angelegt hat michel8
#  0.0.12-2  02.02.2014    Angepasst fuer easyvdr 2.0 und xbmc-12.2 Frodo
#
#  michel8 for easyvdr
#
############################

. /usr/lib/vdr/easyvdr-config-loader
. /usr/lib/vdr/functions/easyvdr-functions-lib
. /usr/share/easyvdr/setup/easyvdr-setup-defines
. /usr/share/easyvdr/setup/easyvdr-setup-functions
. $SETUP_STATUS                                     # Statusfile auslesen



#############################################
# Hier ende bis das Skript angepasst wurde
exit 0


TITLE=" Setup fuer easyVDR $EASYVDR_VERSION - Audio "
BACKTITLE=" Audio Konfiguration fuer easyVDR"

FILENAME="easyvdr-config-audio"
FILENAMEX="xbmc_config_audio"
FILEVERSIONX="V 0.0.12-2 vom 02.02.2014"
SNDLOG="$EASYVDR_LOGDIR/easyvdr-config-audio.log"

xbmc_settings_dir="/home/easyvdr/.xbmc/userdata"
xbmc_settings_file="$xbmc_settings_dir/guisettings.xml"

TMP_XBMC_AudioPar="/tmp/xbmcAudioPar"
TMP_XBMC_Params="/tmp/xbmcParams"

if [[ "x$2" == "x" ]]; then
      echo "Nur als Tochterscript von easyvdr-config-audio oder als postinst von xbmx ausfuehrbar..."
else
  if [[ "$1" == "postinst" && "$2" == "AddOn" && "$Audio_configured" == "true" ]]; then
    echo " " >> $SNDLOG
    echo "************************************************************" >> $SNDLOG
    echo "`date` Aufruf aus der postinst von xbmc" >> $SNDLOG
    echo "************************************************************" >> $SNDLOG
    # in der setup.state sieht es dazu so aus:
    #Audio_configured_PassThrough="hdmi:CARD=NVidia,DevNo:7"
    #Audio_configured_Layout="Stereo 2.0"
  else
    echo "************************************************************" >> $SNDLOG
    echo "     ... Aufruf von $FILENAMEX " >> $SNDLOG
    echo "************************************************************" >> $SNDLOG
    Audio_configured_PassThrough=$1	# ist das PassThrough-Device
    Audio_configured_Layout=$2 		# ist das Boxenlayout
  fi
    echo "File-Info: $FILENAMEX $FILEVERSIONX" >> $SNDLOG
  # Verzeichnis und File bei Nichtvorhandensein erstellen
  if [[ ! -d $xbmc_settings_dir ]]; then
    mkdir -p $xbmc_settings_dir                   >/dev/null 2>&1
    chown easyvdr:easyvdr $xbmc_settings_dir      >/dev/null 2>&1
    chmod 777 $xbmc_settings_dir                  >/dev/null 2>&1
  fi
  if [[ ! -f $xbmc_settings_file ]]; then
    echo "<settings>"                                           >  $xbmc_settings_file
    echo "    <audiooutput>"                                    >> $xbmc_settings_file
    echo "        <ac3passthrough>false</ac3passthrough>"       >> $xbmc_settings_file
    echo "        <audiodevice></audiodevice>"                  >> $xbmc_settings_file
    echo "        <channels>1</channels>"                       >> $xbmc_settings_file
    echo "        <mode>0</mode>"                               >> $xbmc_settings_file
    echo "        <multichannellpcm>true</multichannellpcm>"    >> $xbmc_settings_file
    echo "        <passthroughdevice></passthroughdevice>"      >> $xbmc_settings_file
    #echo "        <dtshdpassthrough>true</dtshdpassthrough>"    >> $xbmc_settings_file
    #echo "        <dtspassthrough>true</dtspassthrough>"        >> $xbmc_settings_file
    #echo "        <guisoundmode>1</guisoundmode>"               >> $xbmc_settings_file
    #echo "        <normalizelevels>true</normalizelevels>"      >> $xbmc_settings_file
    #echo "        <passthroughaac>false</passthroughaac>"       >> $xbmc_settings_file
    #echo "        <stereoupmix>false</stereoupmix>"             >> $xbmc_settings_file
    #echo "        <truehdpassthrough>true</truehdpassthrough>"  >> $xbmc_settings_file
    echo "    </audiooutput>"                                   >> $xbmc_settings_file
    echo "</settings>"                                          >> $xbmc_settings_file
    chmod 644 $xbmc_settings_file
    chown easyvdr:easyvdr $xbmc_settings_file
  fi

    StartSect=$(egrep -n "<audiooutput>" $xbmc_settings_file | awk 'END{print}' | cut -d":" -f1)
    EndSect=$(egrep -n "</audiooutput>" $xbmc_settings_file | awk 'END{print}' | cut -d":" -f1)
#    awk "NR==$StartSect,NR==$EndSect" $xbmc_settings_file > /tmp/xbmcAudioPar1
    awk "NR==$StartSect,NR==$EndSect" $xbmc_settings_file > $TMP_XBMC_AudioPar
    if [[ "$Audio_configured_PassThrough" == "None" ]]; then
      echo "---> xbmc-Audio-Parameter fuer Analog-Only konfigurieren..." >> $SNDLOG
      sed -i "s/^\(.*\)<mode>.*/\1<mode>0<\/mode>/g" $TMP_XBMC_AudioPar # mode=0 => analog
      sed -i "s/^\(.*\)<ac3passthrough>.*/\1<ac3passthrough>false<\/ac3passthrough>/g" $TMP_XBMC_AudioPar
      sed -i "s/^\(.*\)<passthroughdevice>.*/\1<passthroughdevice><\/passthroughdevice>/g" $TMP_XBMC_AudioPar
      #   Optional auch folgende Parameter:
      #        <multichannellpcm>true</multichannellpcm>
      #        <dtshdpassthrough>true</dtshdpassthrough>
      #        <dtspassthrough>true</dtspassthrough>
      #        <passthroughaac>false</passthroughaac>
      #        <truehdpassthrough>true</truehdpassthrough>
    else
      echo "---> xbmc-Audio-Parameter mit PassThrough und..." >> $SNDLOG
      sed -i "s/^\(.*\)<ac3passthrough>.*/\1<ac3passthrough>true<\/ac3passthrough>/g" $TMP_XBMC_AudioPar
      sed -i "s/^\(.*\)<passthroughdevice>.*/\1<passthroughdevice>ALSA:$Audio_configured_PassThrough<\/passthroughdevice>/g" $TMP_XBMC_AudioPar
                       #PassThrough-Parameter:="hdmi:CARD=NVidia,DevNo:7,AES0=0x6,AES1=0x82,AES2=0x0,AES3=0x2"
      if [[ "$(echo $Audio_configured_PassThrough | cut -d: -f1)" == "iec958" ]]; then
        echo "  -> ...fuer SPDIF konfigurieren:" >> $SNDLOG
        sed -i "s/^\(.*\)<mode>.*/\1<mode>1<\/mode>/g" $TMP_XBMC_AudioPar # mode=1 => spdif
        sed -i "s/^\(.*\)<multichannellpcm>.*/\1<multichannellpcm>false<\/multichannellpcm>/g" $TMP_XBMC_AudioPar
      else
        echo "  -> ...fuer HDMI konfigurieren:" >> $SNDLOG
        sed -i "s/^\(.*\)<mode>.*/\1<mode>2<\/mode>/g" $TMP_XBMC_AudioPar # mode=2 => hdmi
        if [[ "$Audio_configured_Layout" == "Stereo 2.0" || "Audio_configured_Layout2" == "2.0/Pass Through" ]]; then
          sed -i "s/^\(.*\)<multichannellpcm>.*/\1<multichannellpcm>false<\/multichannellpcm>/g" $TMP_XBMC_AudioPar
        else
          sed -i "s/^\(.*\)<multichannellpcm>.*/\1<multichannellpcm>true<\/multichannellpcm>/g" $TMP_XBMC_AudioPar
        fi
      fi
      echo "  -> Als Passthroughdevice wird ALSA:$Audio_configured_PassThrough eingestellt..." >> $SNDLOG
    fi
    sed -i "s/^\(.*\)<audiodevice>.*/\1<audiodevice>ALSA:default<\/audiodevice>/g" $TMP_XBMC_AudioPar
    echo "  -> Als Boxenlayout wird $Audio_configured_Layout eingestellt..." >> $SNDLOG

    case  $Audio_configured_Layout in
      "Surround 5.1" | "5.1/Pass Through") No_of_CH=8;; # channells=8 => Surround 5.1
      "Surround 5.0" | "5.0/Pass Through") No_of_CH=7;; # channells=7 => Surround 5.0
      "Surround 4.1" | "4.1/Pass Through") No_of_CH=6;; # channells=6 => Surround 4.1
      "Surround 4.0" | "4.0/Pass Through") No_of_CH=5;; # channells=5 => Surround 4.0
      "Surround 3.1" | "3.1/Pass Through") No_of_CH=4;; # channells=4 => Surround 3.1
      "Surround 3.0" | "3.0/Pass Through") No_of_CH=3;; # channells=3 => Surround 3.0
      "Surround 2.1" | "2.1/Pass Through") No_of_CH=2;; # channells=2 => Surround 2.1
      "Stereo 2.0" | "2.0/Pass Through")   No_of_CH=1;; # channells=1 => Stereo 2.0
                                        *) No_of_CH=1;; # channells=1 => Stereo 2.0
    esac
    sed -i "s/^\(.*\)<channels>.*/\1<channels>$No_of_CH<\/channels>/g" $TMP_XBMC_AudioPar

    #   Optional auch folgende Parameter:
    #        <guisoundmode>1</guisoundmode>
    #        <normalizelevels>true</normalizelevels>
    #        <stereoupmix>false</stereoupmix>

    # guisettings.xml neu zusammenbauen
    awk "NR==1,NR==$StartSect-1" $xbmc_settings_file > $TMP_XBMC_Params
    cat $TMP_XBMC_AudioPar >> $TMP_XBMC_Params
    awk "NR==$EndSect+1,EOF" $xbmc_settings_file >> $TMP_XBMC_Params
    cp $TMP_XBMC_Params $xbmc_settings_file
    echo "---> $xbmc_settings_file wurde neu geschrieben" >> $SNDLOG
    echo "---> Audiokonfiguration von xbmc erfolgt" >> $SNDLOG
    echo "------------------------------------------------------------" >> $SNDLOG
    echo "     $FILENAMEX bis zum Ende durchgelaufen." >> $SNDLOG
    echo "------------------------------------------------------------" >> $SNDLOG
fi
