#!/bin/sh
set -e


if [ "$1" = "configure" ]; then

    # Change owner of directory for temporary files
    /bin/chown -R vdr:vdr /var/lib/vdr/themes || true
	/bin/chown vdr:vdr /var/lib/vdr/plugins/skinsoppalusikka || true


fi

#DEBHELPER#
