#!/bin/sh

echo "CPU:"
top -bci -n 1 | awk '/Cpu\(s\):.*/ { print 100-$8 "% - User " $2 " - System " $4 ;}'
echo
echo "Memory:"
top -bci -n 1 | awk '/Mem:.*/ { print $3/1024 "MB Total   -   "$5/1024 "MB Belegt" ;}'
echo
echo "Swap:"
top -bci -n 1 | awk '/Swap:.*/ { print $3/1024 "MB Total   -   "$5/1024 "MB Belegt" ;}'
echo
echo "Disk Space:"
df -hl | awk '/dev/ {printf("%s : %s von %s frei\n", $1, $4, $2) }'
echo
echo "Tasks:"
top -bci -n 1 | awk '/Aufgaben:.*/ { print $2 " Total    Running " $4 "    Sleep " $6 "    Stopped " $8  ;}'