#!/bin/bash
#gibt noch kein Terminal 8
#chvt 8
echo "[000] prestart.sh v0.4"
#20140415 Code cleanup
#201506-test
#201603-function-lib, generate image
#13.04.2020 disable display-manager Bleifuss



. /usr/lib/vdr/functions/easyvdr-functions-lib
. /usr/lib/vdr/easyvdr-config-loader
IMGDIR=$INSTALLERDIR/images


update_basics(){
cp /etc/apt/sources.list /etc/apt/sources.list.bkp
sed -i 's/^\(.*\)ubuntu.com\(.*\)$/# \1ubuntu.com\2/g' /etc/apt/sources.list
apt-get update
echo "[124] upgrading pre-setup..."
apt-get install --reinstall easyvdr-presetup easyvdr-installer easyvdr
cp /etc/apt/sources.list.bkp /etc/apt/sources.list
}



SERVICE[0]="/etc/systemd/easyvdr/easyvdr-systemstart.service"
SERVICE[1]="/etc/systemd/easyvdr/easyvdr-alsa-restore.service"
SERVICE[2]="/etc/systemd/easyvdr/easyvdr-cleanscreen.service"
SERVICE[3]="/etc/systemd/easyvdr/easyvdr-create-ramdisk.service"
SERVICE[4]="/etc/systemd/easyvdr/easyvdr-save-ramdisk.service"
SERVICE[5]="/etc/systemd/easyvdr/easyvdr-config-display-manager.service"
SERVICE[6]="/etc/systemd/easyvdr/easyvdr-alsa-store.service"
SERVICE[7]="/lib/systemd/system/inputlirc.service"
SERVICE[8]="/lib/systemd/system/lircd-uinput.service"
SERVICE[9]="/lib/systemd/system/lircd.socket"
SERVICE[10]="/lib/systemd/system/lircd.service"
SERVICE[11]="/lib/systemd/system/lircd-setup.service"
SERVICE[12]="/lib/systemd/system/lircmd.service"



 for CHK_SERVICE in ${SERVICE[*]}
 do
  #Pfad vom Service Namen abschneiden
  SERVICE_NAME=${CHK_SERVICE##*/}

  if [ -f $CHK_SERVICE ]; then
   STAT=$(systemctl is-active "$SERVICE_NAME") || true > /dev/null 2>&1
   if [ $STAT != "inactive" ]; then
    systemctl stop "$SERVICE_NAME" || true > /dev/null 2>&1
   fi

   if [ -f "$CHK_SERVICE" ] ;then
    STAT=$(systemctl is-enabled "$SERVICE_NAME") || true > /dev/null 2>&1
    if [ X$STAT == "Xenabled" ]; then
     systemctl disable "$SERVICE_NAME" || true > /dev/null 2>&1
    fi
   fi
  fi
 done
 unset SERVICE
 systemctl daemon-reload

 plymouth --quit

chvt 4
HOST="www.google.de"
echo "[010] Checking Internet-connection... - please wait"
i=1
  while ( ! ping -w 1 $HOST > /dev/null 2>&1 )
    do
       echo "Try $i of 25"
       sleep 2
      (($i == 24)) && break   # Abbruch nach max. 50 Sekunden
       ((++i))
   done



if (! ping -w 1 $HOST > /dev/null 2>&1 ) ; then

echo "Easyvdr need a network connetion for installing"

else 

sleep 5

echo "[020] Internet-connection established"
echo "[030] Checking for new startscript..."
#update_basics
/usr/share/easyvdr/installer/start.sh
fi
