#!/bin/bash
# added USB-Ramdisk 14.07.12  Captain_Beefheart
#  very lot of changes 01.12.12 C.B.
#  some fixes          23.12.12 C.B.
#  changes for Upstart 25.02.18 Bleifuss
#  changes for Systemd 16.09.2020 Bleifuss
#
#description	"umount and save /ramdisk"
#author 		"Uwe Kiehl <uwe@easy-vdr.de> & C.B."


LOGGER="logger -t easyvdr-alsa-restore"

$LOGGER "restoring alsa settings"
if [ -f /var/lib/alsa/asound.state ];then
 /usr/sbin/alsactl restore
fi
