Description: <short summary of the patch>
 TODO: Put a short summary on the line above and replace this paragraph
 with a longer explanation of this change. Complete the meta-information
 with other relevant fields (see below for details). To make it easier, the
 information below has been extracted from the changelog. Adjust it or drop
 it.
 .
 vdr-plugin-squeezebox (0.0.8.git20140130.1533-0yavdr0~precise) precise; urgency=medium
 .
   * new upstream version
Author: Reiner Paulus <flex0r@gmx.net>

---
The information above should follow the Patch Tagging Guidelines, please
checkout http://dep.debian.net/deps/dep3/ to learn about the format. Here
are templates for supplementary fields that you might want to add:

Origin: <vendor|upstream|other>, <url of original patch>
Bug: <url in upstream bugtracker>
Bug-Debian: http://bugs.debian.org/<bugnumber>
Bug-Ubuntu: https://launchpad.net/bugs/<bugnumber>
Forwarded: <no|not-needed|url proving that it has been forwarded>
Reviewed-By: <name and email of someone who approved the patch>
Last-Update: <YYYY-MM-DD>

--- vdr-plugin-squeezebox-0.0.8.git20140130.1533.orig/Makefile
+++ vdr-plugin-squeezebox-0.0.8.git20140130.1533/Makefile
@@ -85,7 +85,7 @@ OBJS = $(PLUGIN).o lmccom.o osd.o menu.o
 
 ### The main target:
 
-all: $(SOFILE) i18n
+all: $(SOFILE) i18n tt
 
 ### Implicit rules:
 
