#! /bin/sh

set -e

case "$1" in
	remove|upgrade|deconfigure)
                # Remove vdr from groups required by the plugin
                /bin/sh /usr/lib/vdr/vdr-groups.sh --remove vdr-plugin-graphlcd
		;;
	failed-upgrade)
		;;
	*)
		echo "prerm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0


