#!/bin/sh -e
set -e

# Check if there are still cfgfiles in /var/lib/vdradmin/ and move them
# to /var/lib/vdradmin-am
if [ ! -f /var/lib/vdradmin-am/vdradmind.conf ]; then
  if [ -f /var/lib/vdradmin/vdradmind.conf ]; then
     mv /var/lib/vdradmin/vdradmind.conf /var/lib/vdradmin-am/
  else
     cp /usr/share/doc/vdradmin-am/examples/vdradmind.conf /var/lib/vdradmin-am/
  fi
fi

if [ ! -e /etc/vdradmin-am/vdradmind.conf ]; then
        ln -s /var/lib/vdradmin-am/vdradmind.conf /etc/vdradmin-am/vdradmind.conf
fi

if [ ! -f /var/lib/vdradmin-am/vdradmind.at ]; then
   if [ -f /var/lib/vdradmin/vdradmind.at ]; then 
      mv /var/lib/vdradmin/vdradmind.at /var/lib/vdradmin-am/
   fi
fi

if [ ! -f /var/lib/vdradmin-am/vdradmind.done ]; then
   if [ -f /var/lib/vdradmin/vdradmind.done ]; then 
      mv /var/lib/vdradmin/vdradmind.done /var/lib/vdradmin-am/
   fi
fi

if [ ! -f /var/lib/vdradmin-am/vdradmind.bl ]; then
   if [ -f /var/lib/vdradmin/vdradmind.bl ]; then 
      mv /var/lib/vdradmin/vdradmind.bl /var/lib/vdradmin-am/
   fi
fi

# ensure that user and group 'vdradmin-am' exist
USER=vdradmin-am
GROUP=vdradmin-am
if ! getent group | grep -q "^$GROUP:" ; then
    echo -n "Adding group $GROUP.."
    addgroup --quiet --system $GROUP
    echo "..done"
fi
if ! getent passwd | grep -q "^$USER:"; then
    echo -n "Adding user $USER.."
    adduser --system --home /var/lib/vdradmin-am --shell /bin/false \
      --gecos "VDRAdmin-am user" --no-create-home \
      --disabled-login --disabled-password \
      --ingroup $GROUP \
      $USER
    echo "...done"
fi

# ensure vdradmind.at (auto timers) exists
ATFILE=/var/lib/vdradmin-am/vdradmind.at
[ -e $ATFILE ] || touch $ATFILE

# ensure that vdradmin's config files have the correct owner
[ ! -d /var/lib/vdradmin-am ] || chown -R $USER:$GROUP /var/lib/vdradmin-am/

# change the permissions of the cfg-file to 0600
[ ! -e /var/lib/vdradmin-am/vdradmind.conf ] || chmod 0600 /var/lib/vdradmin-am/vdradmind.conf

# change the owner and group of the logfile to vdradmin
[ ! -e /var/log/vdradmind.log ] || chown $USER:$GROUP /var/log/vdradmind.log

# make auto timer file "read/writeable" by group vdr and config file readable
# by group "vdr",so that vdr plugins (Autotimeredit plugin) get access
if getent group | grep -q "^vdr:" ; then
    if [ -d /var/lib/vdradmin-am ] ; then
        chgrp -R vdr /var/lib/vdradmin-am
        chmod a=,ug=rwx /var/lib/vdradmin-am
        chmod a=,ug=rw $ATFILE
        CFGFILE=/var/lib/vdradmin-am/vdradmind.conf
        [ -e $CFGFILE ] && chmod a=,u=rw,g=r $CFGFILE
    fi
fi

# ensure that vdradmin's directories have the correct owner
for dir in /var/cache/vdradmin-am /var/log/vdradmin-am /var/lib/vdradmin-am; do
    [ ! -d $dir ] || chown -R $USER:$GROUP $dir
done

##DEBHELPER##
