#!/bin/sh -e
set -e

case "$1" in
    install)
        # Copy /etc/default/vdradmin to /etc/default/vdradmin-am
        if [ ! -f /etc/default/vdradmin-am ] && [ -f /etc/default/vdradmin ]; then
           cp /etc/default/vdradmin /etc/default/vdradmin-am
        fi
    ;;
    upgrade|abort-upgrade)
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

##DEBHELPER##
