/*
 * i18n.c: Internationalization
 *
 * See the README file for copyright information and how to reach the author.
 *
 */

#include "i18n.h"

#if VDRVERSNUM < 10507
const tI18nPhrase Phrases[] = {
// START I18N - automatically generated by po2i18n.pl
  { "Close display after 2 min.",
    "Anzeige nach 2 Min. schließen",
    "",
    "Chiudi schermata dopo 2 min.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Display various system informations",
    "Anzeige von Systeminformationen",
    "",
    "Mostra diverse informazioni di sistema",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Error getting system information",
    "Fehler beim Abfragen der Systeminformationen",
    "",
    "Errore recupero info sistema",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Refresh intervall (s)",
    "Aktualisierungsintervall (s)",
    "",
    "Intervallo aggiornamento (s)",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "System Information",
    "Systeminformationen",
    "",
    "Info sistema",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "please wait",
    "Bitte warten",
    "",
    "Attendere prego...",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
// END I18N - automatically generated by po2i18n.pl
  { NULL }
  };
#endif
