#!/bin/sh
set -e

if [ "$1" = "configure" ]; then


    # Change owner of directory, symlink and chmod
    chmod a+x  /var/lib/vdr/plugins/cdplayer/convert.sh
    chown -R vdr:vdr /var/lib/vdr/plugins/cdplayer

fi

#DEBHELPER#
