#!/bin/bash
#V 0.1  Bleifuss

. /usr/lib/vdr/easyvdr-config-loader

EXEC_CMD=""

if [ x"$LIRC_HW_CONF" = x"irmp_lirc"   ];then
 EXEC_CMD="/usr/lib/easyvdr/easyvdr-start/easyvdr-irmplircd"
fi

if [ x"$LIRC_HW_CONF" = x"irtrans_server"   ];then
 EXEC_CMD="/usr/lib/easyvdr/easyvdr-start/easyvdr-irtrans"
fi

###29.05.2020 restart inputlic devices###
if [ x"$LIRC_HW_CONF" = x"input_lirc"   ];then
 case "$1" in
        start)
                EXEC_CMD="systemctl restart inputlirc.service"
            ;;
        stop)
                EXEC_CMD="systemctl stop inputlirc.service"
            ;;
        status)
                EXEC_CMD="systemctl status inputlirc.service"
            ;;
        restart)
                EXEC_CMD="systemctl restart inputlirc.service"
            ;;
 esac
 shift
fi

###02-01-2020 restart lirc devices###
if [ $(systemctl is-enabled lircd.service) = "enabled"   ];then
 case "$1" in
        start)
                EXEC_CMD="systemctl restart lircd.service lircd.socket"
            ;;
        stop)
                EXEC_CMD="systemctl stop lircd.service lircd.socket"
            ;;
        status)
                EXEC_CMD="systemctl status lircd.service lircd.socket"
            ;;
        restart)
                EXEC_CMD="systemctl restart lircd.service lircd.socket"
            ;;
 esac
 shift
fi

$EXEC_CMD $1

