#!/bin/bash
#201506 Martin
# ensure that user and group 'vdr' exist

USER=vdr
GROUP=vdr
if ! getent group | grep -q "^$GROUP:" ; then
echo -n "Adding group $GROUP.."
addgroup --quiet --system --gid 2000 $GROUP
echo "..done"
fi

if ! getent passwd | grep -q "^$USER:"; then
echo -n "Adding user $USER.."
adduser --system --home /var/lib/vdr --shell /bin/bash \
--gecos "VDR user" --no-create-home \
--disabled-password \
--ingroup $GROUP \
--uid 2000 $USER
#group autologin for lightdm
groupadd -r autologin
gpasswd -a $USER autologin
echo "...done"
fi

# put vdr in group video so that it can access the DVB device nodes
adduser $USER video > /dev/null || true


#############################################################################
######################### Systemd ###########################################

#Ab hier easyvdr service
 SERVICE[0]="/etc/systemd/easyvdr/easyvdr-systemstart.service"
 SERVICE[1]="/etc/systemd/easyvdr/easyvdr-alsa-restore.service"
 SERVICE[2]="/etc/systemd/easyvdr/easyvdr-cleanscreen.service"
 SERVICE[3]="/etc/systemd/easyvdr/easyvdr-create-ramdisk.service"
 SERVICE[4]="/etc/systemd/easyvdr/easyvdr-save-ramdisk.service"
 SERVICE[5]="/etc/systemd/easyvdr/easyvdr-config-display-manager.service"
 SERVICE[6]="/etc/systemd/easyvdr/easyvdr-alsa-store.service"
 SERVICE[7]="/lib/systemd/system/inputlirc.service"
 SERVICE[8]="/lib/systemd/system/lircd-uinput.service"
 SERVICE[9]="/lib/systemd/system/lircd.socket"
 SERVICE[10]="/lib/systemd/system/lircd.service"
 SERVICE[11]="/lib/systemd/system/lircd-setup.service"
 SERVICE[12]="/lib/systemd/system/lircmd.service"

 for CHK_SERVICE in ${SERVICE[*]}
 do
  #Pfad vom Service Namen abschneiden
  SERVICE_NAME=${CHK_SERVICE##*/}

  if [ -f $CHK_SERVICE ]; then
   STAT=$(systemctl is-active "$SERVICE_NAME") || true > /dev/null 2>&1
   if [ $STAT != "inactive" ]; then
    systemctl stop "$SERVICE_NAME" || true > /dev/null 2>&1
   fi

   if [ -f "$CHK_SERVICE" ] ;then
    STAT=$(systemctl is-enabled "$SERVICE_NAME") || true > /dev/null 2>&1
    if [ X$STAT == "Xenabled" ]; then
     systemctl disable "$SERVICE_NAME" || true > /dev/null 2>&1
    fi
   fi
  fi
 done
 unset SERVICE

#DEBHELPER#

