#!/bin/bash
# 
#  Settings 4 IR Trans LCD Displays
#  initial version 24.08.15 by michel8
#################################################


################### LCD eindeutig zuordnen ueber udev-rule
RULES_FILE="/lib/udev/rules.d/92-irtrans.rules"
if [ ! -e $RULES_FILE ]; then
    echo "SUBSYSTEMS==\"usb\", ATTRS{product}==\"IRTrans USB\", SYMLINK+=\"lcd_irtrans\", MODE=\"0660\", GROUP=\"vdr\"" > $RULES_FILE
else
    if [ "$(grep -c "lcd_irtrans" $RULES_FILE)" == "0" ]; then
      echo "SUBSYSTEMS==\"usb\", ATTRS{product}==\"IRTrans USB\", SYMLINK+=\"lcd_irtrans\", MODE=\"0660\", GROUP=\"vdr\"" >> $RULES_FILE
    fi
fi

################### LCD aus bei Powerdown
SHUTDOWN_FILE="/usr/share/vdr/shutdown-hooks/10_shutdown.custom"
if [ "$(grep -c "/etc/init.d/LCDd stop" $SHUTDOWN_FILE)" == "0" ]; then
    echo "# SHUTDOWNCMD=sudo /etc/init.d/LCDd stop >/dev/null && sleep 1 && echo -n \" \" >/dev/lcd_irtrans; exit 0" >> $SHUTDOWN_FILE
    echo "# SHUTDOWNCMD=sudo /etc/init.d/LCDd stop >/dev/null && sleep 1; exit 0" >> $SHUTDOWN_FILE
    echo "SHUTDOWNCMD=sudo killall LCDd >/dev/null && sleep 1; exit 0" >> $SHUTDOWN_FILE
fi

################### LCDd.conf fuer das IR Trans LCD konfigurieren:
LCDd_CONF_FILE="/etc/LCDd.conf"
if [ ! -e $LCDd_CONF_FILE.default ]; then
    cp $LCDd_CONF_FILE $LCDd_CONF_FILE.default
else
    cp -f $LCDd_CONF_FILE.default $LCDd_CONF_FILE
fi

sed -i '/^Arguments="/d' $LCDd_CONF_FILE						# kommt manchmal vor, dann weg
sed -i '0,/^Driver=.*/s/^Driver=.*/Driver=irtrans\
Arguments="-hostname localhost -lcdw 16 -lcdh 2 -backlight -timeout 1"/' $LCDd_CONF_FILE #nur das erste Vorkommen
#hostname: IP / Hostname of irserver
#lcdw: Breite des LCD Displays (default=16)
#lcdh: Höhe des LCD Displays (default=4)

sed -i '0,/.*Foreground=.*/s/.*Foreground=.*/Foreground=yes/' $LCDd_CONF_FILE 		# nur das erste Vorkommen

sed -i '/^InitialBacklight=/d' $LCDd_CONF_FILE						# kommt nur manchmal vor,
sed -i '/^BacklightBrightness=/d' $LCDd_CONF_FILE					#   dann weg
sed -i '/^BacklightOffBrightness=/d' $LCDd_CONF_FILE					#   und neu
sed -i '0,/.*Backlight=.*/s/.*Backlight=.*/Backlight=on\nInitialBacklight=on\
BacklightBrightness=255\nBacklightOffBrightness=0/' $LCDd_CONF_FILE 			#   und zusammen mit dem 1. Vorkommen neu

sed -i 's/.*ServerScreen=.*/ServerScreen=no/g' $LCDd_CONF_FILE				# kommt nur einmal vor

sed -i '/^InitialHeartbeat=/d' $LCDd_CONF_FILE						# kommt nur manchmal vor, dann weg
sed -i 's/.*Heartbeat=.*/Heartbeat=off\nInitialHeartbeat=off/g' $LCDd_CONF_FILE		#   und zusammen mit dem einen Vorkommen neu

sed -i '0,/.*GoodBye=.*/s/.*GoodBye=.*/GoodBye_TMP=/' $LCDd_CONF_FILE 			# nur das erste behalten,
sed -i '/.*GoodBye="/d' $LCDd_CONF_FILE							#    alle anderen entfernen,
sed -i 's/^GoodBye_TMP=.*/GoodBye="    EasyVDR"\
GoodBye="  Mediacenter"/g' $LCDd_CONF_FILE						#    und das eine Vorkommen anpassen

sed -i '0,/.*Hello=.*/s/.*Hello=.*/Hello_TMP=/' $LCDd_CONF_FILE 			# nur das erste behalten,
sed -i '/.*Hello="/d' $LCDd_CONF_FILE							#    alle anderen entfernen,
sed -i 's/^Hello_TMP=/Hello="  Welcome to"\
Hello="    EasyVDR"/g' $LCDd_CONF_FILE							#    und das eine Vorkommen anpassen

################### LCDd starten:
if [ ! -e /dev/lcd_irtrans ]; then
    /usr/share/easyvdr/setup/hw-detect/udev-reloader
fi
(pidof LCDd > /dev/null 2>&1) && /etc/init.d/LCDd stop > /dev/null 2>&1; sleep 1
/etc/init.d/LCDd start > /dev/null 2>&1
