#!/bin/bash
#
#  Settings 4 Crystalfontz Displays
#  initial version 08.06.15 by michel8
#  Start & GoodBye-Message 23.08.15 by michel8
#  Crystalfontz added by gb 17.02.2018 & thank you michel8 for a good preparation
#################################################


################### LCD eindeutig zuordnen ueber udev-rule
RULES_FILE="/lib/udev/rules.d/92-Crystalfontz.rules"
if [ ! -e $RULES_FILE ]; then
echo "KERNEL==\"lcd*\", ATTRS{idVendor}==\"0403\", ATTRS{idProduct}==\"*\", SYMLINK+=\"Crystalfontz\", MODE=\"0660\", GROUP=\"vdr\"" > $RULES_FILE
else
if [ "$(grep -c "Crystalfontz" $RULES_FILE)" == "0" ]; then
 echo "KERNEL==\"lcd*\", ATTRS{idVendor}==\"0403\", ATTRS{idProduct}==\"*\", SYMLINK+=\"Crystalfontz\", MODE=\"0660\", GROUP=\"vdr\"" >> $RULES_FILE
fi
fi

################### LCD aus bei Powerdown
SHUTDOWN_FILE="/usr/share/vdr/shutdown-hooks/10_shutdown.custom"
if [ "$(grep -c "/dev/Crystalfontz" $SHUTDOWN_FILE)" == "0" ]; then
  echo "SHUTDOWNCMD=sudo /etc/init.d/LCDd stop >/dev/null && sleep 1 && echo -n \" \" >/dev/Crystalfontz; exit 0" >> $SHUTDOWN_FILE
fi

################### LCDd.conf fuer das Crystalfontz konfigurieren:
LCDd_CONF_FILE="/etc/LCDd.conf"
if [ ! -e $LCDd_CONF_FILE.default ];then
  cp $LCDd_CONF_FILE $LCDd_CONF_FILE.default
else
  cp -f $LCDd_CONF_FILE.default $LCDd_CONF_FILE
fi
sed -i '0,/^Driver=.*/s/^Driver=.*/Driver=CFontz/' $LCDd_CONF_FILE            # nur das erste Vorkommen
sed -i 's/.*ServerScreen=.*/ServerScreen=off/g' $LCDd_CONF_FILE                # kommt nur einmal vor
sed -i 's/Device=\/dev\/lc.*/Device=\/dev\/Crystalfontz/g' $LCDd_CONF_FILE            # alle Vorkommen

sed -i '0,/.*GoodBye=.*/s/.*GoodBye=.*/GoodBye_TMP=/' $LCDd_CONF_FILE             # nur das erste behalten,
sed -i '/.*GoodBye="/d' $LCDd_CONF_FILE                            #    alle anderen entfernen,
sed -i 's/^GoodBye_TMP=.*/GoodBye="    EasyVDR"\
GoodBye="  Mediacenter"/g' $LCDd_CONF_FILE                        #    und das eine Vorkommen anpassen

sed -i '0,/.*Hello=.*/s/.*Hello=.*/Hello_TMP=/' $LCDd_CONF_FILE             # nur das erste behalten,
sed -i '/.*Hello="/d' $LCDd_CONF_FILE                            #    alle anderen entfernen,
sed -i 's/^Hello_TMP=/Hello="  Welcome to"\
Hello="    EasyVDR"/g' $LCDd_CONF_FILE                            #    und das eine Vorkommen anpassen


################### LCDd starten:
if [ ! -e /dev/Crystalfontz ]; then
  /usr/share/easyvdr/setup/hw-detect/udev-reloader
fi
(pidof LCDd > /dev/null 2>&1) && /etc/init.d/LCDd stop > /dev/null 2>&1; sleep 1
/etc/init.d/LCDd start > /dev/null 2>&1

