#!/bin/bash
#
# Dieses Skript konfiguriert die Ausgabe über "X"
#
#  Captain_Beefheart fuer easyvdr 0.9
#
#
# Version 0.0.3 - sinai,sirnova,C.B.
#  V 0.0.4 11.02.13  C.B.
# 
#
################################################
#defines

. /usr/lib/vdr/easyvdr-config-loader
. /usr/lib/vdr/functions/easyvdr-functions-lib
. /usr/share/easyvdr/setup/easyvdr-setup-defines
. /usr/share/easyvdr/setup/easyvdr-setup-functions

###################### main ########################## 

WriteStatus "Meta_standard-x-out" "X_configured"

