#!/bin/bash
#
#
# Version 0.0.2 - sinai,sirnova,C.B.: added set frontend & OSD selection
# V       0.0.3  11.02.13  C.B.
# 
#################################################

################################# defines ##########################################

. /usr/lib/vdr/easyvdr-config-loader
. /usr/lib/vdr/functions/easyvdr-functions-lib
. /usr/share/easyvdr/setup/easyvdr-setup-defines
. /usr/share/easyvdr/setup/easyvdr-setup-functions

####################################

apt-get --yes remove --purge vdr-skins-1920
apt-get --yes remove --purge vdr-plugin-music
apt-get --yes remove --purge vdr-plugin-play
apt-get --yes remove --purge vdr-plugin-undelete
apt-get --yes remove --purge vdr-plugin-skinflat
apt-get --yes remove --purge vdr-plugin-skinflatplus
apt-get --yes remove --purge vdr-plugin-skinnopacity
apt-get --yes remove --purge vdr-plugin-tvguide

WriteStatus "Meta_dvbsd-out" "DVB_FF_configured"


