#!/bin/bash
# 
#
# Version 0.0.2 - sinai,sirnova,C.B.: added set frontend & OSD selection
#  V      0.0.3    11.02.13  C.B.
#
#################################################

################################# defines ##########################################

. /usr/lib/vdr/easyvdr-config-loader
. /usr/lib/vdr/functions/easyvdr-functions-lib
. /usr/share/easyvdr/setup/easyvdr-setup-defines
. /usr/share/easyvdr/setup/easyvdr-setup-functions

####################################

WriteStatus "Meta_dvbhd-out" "DVBS2_FF_configured"

