#!/bin/bash
#
#
#  v. 0.1
#   michel8@easy-vdr.de
#  31.03.16
# 
#  according to 
#  http://www.easy-vdr.de/forum/18479/fernbedienung-ms-tech-380/msg174171/#msg174171
#
#################################################

modprobe -r -q hid-mstech
unzip -q -u hid-mstech-0.0.1.zip -d/usr/src
sudo dkms -q add -m hid-mstech -v 0.0.1
sudo dkms -q build -m hid-mstech -v 0.0.1
sudo dkms -q install -m hid-mstech -v 0.0.1
if [ $(grep -c "hid-mstech" /etc/initramfs-tools/modules) == 0 ]; then
    echo "hid-mstech" >> /etc/initramfs-tools/modules
fi
sudo sh -c 'echo "install usbhid /sbin/modprobe hid-mstech ; sbin/modprobe -i usbhid ; true" > /etc/modprobe.d/hid-mstech.conf'
sudo update-initramfs -u  > /dev/null 2>&1
modprobe -q hid-mstech
