#!/bin/bash

#--------------------------------------------
# Dieses Skript konfiguriert den Atric USB-Empfaenger fuer die FB
#---------------------------------------------
# Version:      0.1.0 fuer easyVDR 2.1
#---------------------------------------------
# Autor:        michel8
#---------------------------------------------
#
#
########################################################

. /usr/lib/vdr/easyvdr-config-loader
. /usr/lib/vdr/functions/easyvdr-functions-lib
. /usr/share/easyvdr/setup/easyvdr-setup-defines
. /usr/share/easyvdr/setup/easyvdr-setup-functions

#. $SETUP_STATUS                                     # Statusfile auslesen
. $CFG_DIR/sysconfig
LIRCD_DIR="$CFG_DIR/remotes"
Target="/dev/input/ir-auto_dtc"    #"/dev/ttyACM0"


Get_FB_Params()
{
LircConfFile="$LIRCD_DIR/$FB_CONTROLLER/lircd.conf.irman"

if [ -f $LircConfFile ]; then
    Atric_FB_Name_Str=$(grep "Atric_FB_Name_Str" $LircConfFile | cut -d\" -f 2 )
    Atric_FB_Conf_Str=$(grep "Atric_FB_Conf_Str" $LircConfFile | cut -d\" -f 2 )
    Atric_FB_Pwr_On_0=$(grep "Atric_FB_Pwr_On_0" $LircConfFile | cut -d\" -f 2 )
else
    Atric_FB_Name_Str=""
    Atric_FB_Conf_Str=""
    Atric_FB_Pwr_On_0=""
fi
}

WriteConfToAtricUSB()
{
TempConf="/tmp/atric_tmpC"
TempConf2="/tmp/atric_tmpC2"
printf "%s" "$Kommando" > $TempConf

Data="$(echo $HexVal | sed 's/\([0-9a-zA-Z][0-9a-zA-Z]\)/\1\n/g' | while read PAIR ; do 
printf "$PAIR "
done)"
for i in $Data; do
    if [ "$i" == "00" ]; then
	dd if=/dev/zero of=$TempConf2 bs=1 count=1 > /dev/null 2>&1
	cat $TempConf2 >> $TempConf && rm $TempConf2
    else
        printf "\x$i" >> $TempConf
    fi
done
dd if=$TempConf of=$Target > /dev/null 2>&1
rm $TempConf
}

WritePowerOnToAtricUSB()
{
TempConf="/tmp/atric_tmpC"
TempConf2="/tmp/atric_tmpC2"
#   Schreibe Schaltfunktion_0
printf "%s" "$Kommando" > $TempConf
Aktion="00 "		# Schaltaktion_0
Data=$Aktion"$(echo $HexVal | sed 's/\([0-9a-zA-Z][0-9a-zA-Z]\)/\1\n/g' | while read PAIR ; do 
printf "$PAIR "
done)"
for i in $Data; do
    if [ "$i" == "00" ]; then
	dd if=/dev/zero of=$TempConf2 bs=1 count=1 > /dev/null 2>&1
	cat $TempConf2 >> $TempConf && rm $TempConf2
    else
        printf "\x$i" >> $TempConf
    fi
done
dd if=$TempConf of=$Target > /dev/null 2>&1
rm $TempConf

#   Schreibe Anzahl der Schaltfunktionen
printf "%s" "$KommandoN" > $TempConf
printf "\x01" >> $TempConf			# nur eine Funktion 
dd if=$TempConf of=$Target > /dev/null 2>&1
rm $TempConf
}


##################################################################
##  main

if [[ -e $Target && "$FB_RECEIVER" == "Atric_IR_Wakeup_USB" ]]; then
    Get_FB_Params
    Kommando="LACS"	# IR-Empfang abschalten
    echo "$Kommando" > $Target
    sleep 1
    if [ "$Atric_FB_Name_Str" != "" ]; then
        Kommando="FNSACS"	# Schreibe den FB-Namen
        TempConf="/tmp/atric_tmpC"
        printf "%s" "$Kommando$Atric_FB_Name_Str" > $TempConf
        dd if=$TempConf of=$Target > /dev/null 2>&1
        rm $TempConf
	# echo "Writing Name $Atric_FB_Name_Str to Atric-USB:"
	# echo "$Kommando$Atric_FB_Name_Str"
        sleep 1
    fi
    if [ "$Atric_FB_Conf_Str" != "" ]; then
	Kommando="FPSACS"	#   Schreibe die FB-Konfiguration
	HexVal=$Atric_FB_Conf_Str
	WriteConfToAtricUSB
        sleep 1
	# echo "Writing $Atric_FB_Name_Str - Parameter to Atric-USB:"
	# echo $Atric_FB_Conf_Str
    fi
    if [ "$Atric_FB_Pwr_On_0" != "" ]; then
        KommandoN="SCSACS"	#   Schreibe Anzahl der Schaltfunktionen
	Kommando="SASACS"	#   Schreibe die Power-On-Konfiguration
	HexVal=$Atric_FB_Pwr_On_0
	WritePowerOnToAtricUSB
	# echo "PowerOn:"
	# echo "Atric_FB_Pwr_On_0: $Atric_FB_Pwr_On_0"
        sleep 1
    fi
    Kommando="C"		# IR-Empfang eischalten
    echo "$Kommando" > $Target
fi

