#!/bin/bash

#--------------------------------------------
# Wenn fien FB-Receiver, dann auch kein FB-Controller
#---------------------------------------------
# Version:      0.1.0 fuer easyVDR 2.1
#---------------------------------------------
# Autor:        michel8
#---------------------------------------------
#
#
########################################################

. /usr/lib/vdr/easyvdr-config-loader
. /usr/lib/vdr/functions/easyvdr-functions-lib
. /usr/share/easyvdr/setup/easyvdr-setup-defines
. /usr/share/easyvdr/setup/easyvdr-setup-functions

#. $SETUP_STATUS                                     # Statusfile auslesen

SetSysconfig FB_CONTROLLER __keine_Fernbedienung
SetVDRSetupXML FB_CONTROLLER __keine_Fernbedienung
