#!/bin/bash
# 
#################################################

## aktiviert die erforderlichen Plugins sundtek und dynamite

. /usr/lib/vdr/easyvdr-config-loader
. /usr/lib/vdr/functions/easyvdr-functions-lib
. /usr/share/easyvdr/setup/easyvdr-setup-defines
. /usr/share/easyvdr/setup/easyvdr-setup-functions

ActivatePlugin sundtek
ActivatePlugin dynamite
