#!/bin/bash
#
# mango 10.04.2012
# scripte *.m3u to *.pls
# mango 01.03.2020 added pyhton3
#

# VDR-OSD-Mitteilung.
/usr/bin/svdrpsend mesg  "Playlisten erstellen gestartet..."

rm -rf /tmp/vtn

sleep 0.2
find /usr/share/vdr-netradio/net-radio.py -exec grep ").m3u" {} \; -exec sed -i "s/).m3u/).pls/g" {} \;

sleep 0.2
python3 /usr/share/vdr-netradio/net-radio.py



 
