#!/bin/bash
#
# mango 10.04.2012
# scripte *.pls to .*m3u
# mango 01.03.2020 added pyhton3
#

# VDR-OSD-Mitteilung.
/usr/bin/svdrpsend mesg  "Playlisten erstellen gestartet..."

rm -rf /tmp/vtn

sleep 0.2

find /usr/share/vdr-netradio/net-radio.py -exec grep ").pls" {} \; -exec sed -i "s/).pls/).m3u/g" {} \;

sleep 0.2
python3 /usr/share/vdr-netradio/net-radio.py



 
