#!/bin/sh
# postinst script for vdr-plugin-externalplayer
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
. /usr/share/debconf/confmodule

case "$1" in
	configure)
		# ensure that the config-dir is correctly owned
		chown -R vdr:vdr /usr/share/vdr-plugin-externalplayer || true
		chown vdr:vdr /var/lib/vdr/plugins/externalplayer.conf || true
		rm -rf /var/lib/vdr/plugins/externalplayer
	;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
