#!/bin/bash
#
# Setup fuer easyvdr Haupt-/Steuerungsteil
#
# Version:      0.0.1 fuer easyVDR 0.9 michel8
#               0.0.9 01.08.11 Captain_Beefheart
#               0.1.0 02.09.11 michel8: incl. Logging
#               0.1.1 21.09.11 Captain_Beefheart: Fix 4 make-media-dirs
#               0.1.2 06.10.11 C.B. added patch for easyvdr-portal
#               0.1.3 18.10.11 C.B. added chmod 666 $SETUPLOG
#               0.2   21.10 11 C.B. setup-break for progress on another teminal
#               0.2.1 21.11.11 C.B. added Stop_X_Windows
#               0.2.2 07.01.12 C.B. moved Stop_X-Windows to other postion
#               0.2.3 10.02.12 C.B. sleep 5 after VDR start
#               0.2.4          C.B  deny start on X-terminal ( Check_Console() )
#               0.3   31.03.12 C.B. Added choose desktop
#               0.3.1 28.04.12 C.B. removed lighttp patch, added osd-skin
#               0.3.2 13.05.12 C.B. fix for FF & X1 paralell
#               0.3.3 14.05.12 C.B. fix2 for FF & X1 paralell
#               0.3.4 16.05.12 C.B. added PChanger support
#               0.3.5 16.06.12 Martin Exclude Kernel-Updates
#               0.3.6 26.06.12 sinai & c.b. added Softhddevice & keines
#               0.3.7 05-08-12 C.B. PChanger in der Inst
#               0.3.8 25-01-13 C.B  new defines and small fix (display version on hw-detect menu)
#               0.3.8 28-11-13 Bleifuss added Monitor-Layout and Video-details
#               0.3.9 19-01-14 michel8: AddOnVerwaltung aus der erstconfig entfernt
#               0.9.00 02-03-14 martin: setup starter as wrapper, same version as in package
#               0.9.01 20-03-14 michel8: Errordetect in HW-Erkennung
#               0.9.04 14-04-14 michel8: Network als letztes im Setup
#               0.9.05 01-05-14 michel8: Erweiterte FB-Konfiguration ergaenzt
#               0.9.06 01-05-14 michel8: Setup mit Untermenus
#               0.9.07 16-05-14 michel8: Erweiterte FB-Konfiguration nur bei x-Systemen
#               0.9.07 09-12-14 Bleifuss: VDR_Start geändert
#               0.9.07 17-01-15 Stopp Desktop beim start von Setup
#               0.9.10 14-05-15 Keine FB vermeidet Aufruf der erweiterten FB-Einstellungen
#               0.9.11 14-05-15 pidof now quiet
#               0.9.12 22-03-16 typo
#               0.9-13 08.10.17 systemd update
#############################################################################

############################## defines ######################################
. /usr/lib/vdr/easyvdr-config-loader
. /usr/lib/vdr/functions/easyvdr-functions-lib
. /usr/share/easyvdr/setup/easyvdr-setup-defines
. /usr/share/easyvdr/setup/easyvdr-setup-functions

TITLE=" Setup fuer easyVDR $EASYVDR_VERSION - Hauptmenue "
BACKTITLE=" Setup fuer easyVDR"

FILENAME="easyvdr-setup"
FILEVERSION="V 0.9.12  vom 22.03.2016"
SETUPLOG="$EASYVDR_LOGDIR/easyvdr-setup.log"

RUN_OPTION=$1

echo " " 								  >> $SETUPLOG
echo "-------------------------------------------------- " 		  >> $SETUPLOG
echo "File-Info: $FILENAME $FILEVERSION" 		  		  >> $SETUPLOG
echo "`date` Zentrales Setup-Script gestartet: $FILENAME $RUN_OPTION"	  >> $SETUPLOG

############################### functions ##########################################

#####
Master_of_Desaster()
{
ROOT_STAT=0
if [ "`id -u`" != "0" ]; then
  dialog --backtitle "$BACKTITLE"\
         --title " ERROR: No Root"\
         --no-cancel\
         --pause " \n\n\n\
        Bitte starten Sie das Setup mit Administratorrechten \n\n\n\
                 also z.B. mit vorangestelltem \"sudo\" " $DIA_BOX2_SIZE $TIMEOUT2
  clear
  ROOT_STAT=1
  echo "`date` Setup wurde ohne Admin-Rechte gestartet => Abbruch..." >> $SETUPLOG
fi
}

#####
Run_On_Install()
{
RET_STAT=1
grep -q "ENABLED=\"yes\"" /etc/default/vdr && VDR_START_STAT=0 || VDR_START_STAT=1
#Prüfen ob Setup über Systemd gestartet wurde
systemctl is-active easyvdr-setup-call.service > /dev/null 2>&1
if [ $? -eq 0 ] && [ $VDR_START_STAT -eq 1 ]; then
 DisableSystemd
 RET_STAT=0
fi
}

#####
Check_Console()
{
CURRENT_CONSOLE=$(fgconsole)         ## aktuell aktives Terminal
CONSOLE_STAT=0

if (($CURRENT_CONSOLE == 7)) && (check_x_running > /dev/null 2>&1) && [ ! -z "$DISPLAY" ]; then        ## 7 <=> "X" 
    dialog --backtitle "$BACKTITLE"\
           --title " ERROR: started on X-Terminal"\
           --no-cancel\
           --pause " \n\n\
#********************************************************************#\n\n\
 Bitte starten Sie das Setup nicht von einer X-Terminalemulation aus!\n\
    Wegen eines Fehlers in Xorg kann dieses zu Problemen fuehren.\n\n\
           Benutzen Sie statt dessen eine \"echte\" Console.\n\
               (also z.B. mit <Strg> <Alt> <F2>)\n\
        oder eine \"remote\" Console (z.B. putty oder rlogin )\n\n\
#********************************************************************#" $DIA_BOX2_SIZE $TIMEOUT3
  clear
  CONSOLE_STAT=1
  echo "`date` Setup wurde auf xterm gestartet => Abbruch..." >> $SETUPLOG
fi
}

#####
Build_Files()
{
echo "`date` -  start setup-script: easyvdr-make-media-dirs" >> $SETUPLOG
$SETUP/easyvdr-make-media-dirs

if [ -f $SETUP_STATUS ]
  then 
    . $SETUP_STATUS
  else
    echo "# `date` Setup-Status-File neu angelegt" > $SETUP_STATUS
    echo "`date` Setup-Status-File neu angelegt" >> $SETUPLOG
    chmod 666 $SETUPLOG
fi
}

#####
Pre_Main()
{
echo "`date` Toolmenu aktivieren..." >> $SETUPLOG
if (! grep -q "easyvdr-toolmenu" /home/easyvdr/.bash_profile); then
  echo "$SETUP/toolmenu/easyvdr-toolmenu" >> /home/easyvdr/.bash_profile
fi
}

#####
Run_HW_Detect()
{
echo "`date` -  start HW-Detect-Script: easyvdr-detect"       >> $SETUPLOG
$DETECT/easyvdr-detect
}

#####
Check_Install_Log()
{
HW_DETECT_LOG="$EASYVDR_LOGDIR/easyvdr-HW-detect_install.log"
if [ $(grep -c "E: Fehler beim Installieren von:" $HW_DETECT_LOG) == 0 ]; then
    HW_Detect_Install_Errorfree="true"
else
    echo "`date` Paketinstallation nach Hardware Erkennung fehlerhaft" >> $SETUPLOG
    dialog --backtitle "$BACKTITLE"\
       --title " Setup fuer easyVDR $EASYVDR_VERSION - hw-detect "\
       --yes-label " HW-Erkennung erneut starten "\
       --no-label " Setup abbrechen "\
       --yesno "\n\n\
                   Fehler bei Paketinstallation !!! \n\n\
      Zur Fehlerdiagnose mit [Strg][Alt][F2] auf andere Konsole\n\
                 und dort die HW-Erkennung abbrechen. \n\n\
  In den Logfiles /var/log/easyvdr/easyvdr-HW-detect_install.log und\n\
  */apt-get.log nach Problemen suchen und diese zu beheben versuchen.\n\n\
               Dann hierher zurueck mit [Strg][Alt][F8] \n\
                  und HW-Erkennung erneut starten,\n
    oder mit Setup abbrechen hier die Erstkonfiguration beenden." $DIA_BOX2_SIZE
    YESNO=$?
    clear
    if (( $YESNO != 0 )); then
	HW_Detect_Install_Errorfree="exit"
    fi
fi
}

#####
Sub_Main()
{
echo "`date` -  starte HW-config-script: easyvdr-config-K8-minimalfrequency" >> $SETUPLOG
$HW_SETUP_SP/easyvdr-config-K8-minimalfrequency       # Setzt min. Frequenz fuer AMD K8 CPU
}

#####
Main()
{
Main_Intro_Menu
Sub_Main
i=0
while (( $i != 1 ))
  do
     . $SETUP_STATUS
    [ "$Video_in_configured"       != "true" ] && Video_in_set   || i=1
    [ "$Video_con_configured"      != "true" ] && Video_con_set  || i=$(( 1 && $i ))
    [ "$Video_out_configured"      != "true" ] && Video_out_set  || i=$(( 1 && $i ))
    [ "$Monitor_layout_configured" != "true" ] && M_layout_set   || i=$(( 1 && $i ))
    [ "$Video_details_configured"  != "true" ] && Video_detal_set|| i=$(( 1 && $i ))
    [ "$OSD_configured"            != "true" ] && OSD_skin_set   || i=$(( 1 && $i ))
    [ "$Audio_configured"          != "true" ] && Audioset       || i=$(( 1 && $i ))
    [ "$Channellist_Selected"      != "true" ] && Chlistset      || i=$(( 1 && $i ))
    [ "$Infodisplay_configured"    != "true" ] && Infodisplayset || i=$(( 1 && $i ))
    [ "$RemoteReceiver_configured" != "true" ] && Fb_Receiverset || i=$(( 1 && $i ))
    [ "$RemoteControl_configured"  != "true" ] && Fb_Controllset || i=$(( 1 && $i ))
    [ "$PChanger_configured"       != "true" ] && PChangeset     || i=$(( 1 && $i ))
    [ "$Network_configured"        != "true" ] && Netzwerkset    || i=$(( 1 && $i ))
#    [ "$Addon_Manager_Selected"    != "true" ] && Addonsset      || i=$(( 1 && $i ))
  done

Ask_Adv_FB_CONFIG

Show_Force_Box
clear
}

#####
Ask_Adv_FB_CONFIG()
{
Get_Frontend_Class	# liest auch die Fernbedienung aus der sysconfig
if [[ "$FRONTEND_CLASS" == "USE_X11" && "$FB_CONTROLLER" != "__keine_Fernbedienung" ]]; then
    dialog --backtitle "$BACKTITLE"\
       --title " Erweiterte FB-Konfiguration "\
       --yes-label " Starte Konfiguration "\
       --no-label " Nein, jetzt nicht "\
       --yesno "\n\n\
              Weitere Funktionen der Fernbedienung:\n\n\
         Fuer KODI und den PChanger koennen jetzt weitere\n\
               Einstellungen vorgenommen werden.\n\n\
            Dazu muessen Tasten der Fernbedienung\n\
           in Reichweite des VDR gedrueckt werden.\n\n\
         Diese Konfiguration kann aber auch spaeter\n\
        ueber das Toolmenu (erneut) gestartet werden." $DIA_BOX2_SIZE
    YESNO=$?
    clear
    if (( $YESNO == 0 )); then
	Adv_Fb_Config
	clear
    fi
fi

}

#####
Show_Force_Box()
{
dialog --backtitle "$BACKTITLE"\
       --pause " \n\n\n\
                    Die Erstinstallation ist beendet. \n\n\n\
       Falls Sie weitere Feineinstellungen oder Aenderungen vornehmen \n\
         oder weitere Plugins und AddOns installieren wollen,\n\n\
            so starten Sie bitte die Konfiguration erneut mit \n\n\
            \"sudo setup\" oder ueber das easyVDR Tool-Menue  ." $DIA_BOX2_SIZE $TIMEOUT2
clear
}

#####
Show_Countdown()
{
  { 
  i=100
  while (( $i>0 ))
    do 
      echo $i; sleep 0.03; i=$(( $i -1 ))
    done 
  echo 0; 
  } | dialog --backtitle "          Reboot Information" \
             --gauge "    System wird in 3 Sekunden\n    neu gestartet" $DIA_BOX_SIZE
clear
OK_CANCEL=1
}

#####
Detect_Intro_Menu()
{
echo "`date` Hardware Erkennung starten:" >> $SETUPLOG
dialog --backtitle "$BACKTITLE"\
       --title " Setup fuer easyVDR $EASYVDR_VERSION - hw-detect "\
       --yes-label " Hardware Erkennung starten "\
       --no-label " Unterbrechung "\
       --yesno "\n\n\
                   Hardware-Detection fuer easyVDR \n\n\
                               Hallo!\n\
          Die Linux-Grundkonfiguration ist jetzt abgeschlossen.\n\
             Als naechstes wird nun Ihr easyVDR eingerichtet.\n\n\
                  Bitte starten Sie nun die HW-Erkennung.\n\
        Falls Sie \"Unterbrechung\" auswaehlen oder <ESC> druecken\n\
         koennen Sie das Setup an einem anderen Terminal fortsetzen " $DIA_BOX2_SIZE
YESNO=$?
clear
}

#####
Main_Intro_Menu()
{
echo "`date` Einstellungen und Anpassungen:" >> $SETUPLOG
dialog --backtitle "$BACKTITLE"\
       --title "$TITLE"\
       --ok-label " Setup "\
       --msgbox "\n\n\
                    Einstellungen und Anpassungen \n\n\
                 ... und wieder ein Schritt weiter ;-)\n\
         Im Folgenden werden Sie nach einigen nicht automatisch\n\
           konfigurierbaren Eigenschaften/Einstellungen gefragt.\n\n\
                    Bitte starten Sie nun das Setup." $DIA_BOX2_SIZE
}

#####
Intro_Menu()
{
echo "`date` Info: Setup wurde von der Konsole oder aus dem Toolmenue manuell gestartet" >> $SETUPLOG
dialog --backtitle "$BACKTITLE"\
       --title "$TITLE"\
       --no-label " Abbruch "\
       --yes-label " setup "\
       --yesno "\n\n\
                          Setup fuer easyVDR \n\n\
              Im Folgenden koennen Sie weitere Einstellungen\n\
                       an Ihrem VDR vornehmen.\n\
                  Hierfuer muss der VDR gestoppt werden.\n\
            Falls Sie gerade z.B. eine TV-Sendung aufzeichnen\n\
                 sollten Sie an dieser Stelle abbrechen." $DIA_BOX2_SIZE
YES_NO=$?
clear
if (( $YES_NO == 0 ))
  then
    INFO_TXT="\n\n\n \Zb\Z1   VDR wird gestoppt"
    MiniInfo " working " "$BACKTITLE" "$INFO_TXT"
    echo "`date` Stoppe X, VDR und Frontend..." >> $SETUPLOG
    systemctl stop easyvdr-systemstart >/dev/null 2>&1
    easyvdr-frontend stop >/dev/null 2>&1
    easyvdr-vdr stop      >/dev/null 2>&1
    Stop_X_Windows
    OK_CANCEL=0 
  else
    OK_CANCEL=1
fi
}

#####
Menu()
{
Intro_Menu

while (( $OK_CANCEL == 0 ))
do
  SET_MENUITEM=$(dialog \
        --backtitle "$BACKTITLE"\
        --title "$TITLE"\
        --cancel-label "Setup abbrechen" \
        --menu "\
      Steuerung mit:                     [   UP   ] [ DOWN ] \n\
      Zum Auswaehlen:                    <  OK  > \n\
      Beenden, ohne den VDR zu starten:  < Abbrechen > "  $DIA_BOX_SIZE \
    Video_in       "TV-Karten konfigurieren"                            \
    Video_connect  "TV-Karten auswaehlen"                               \
    AudioVideo_out "Video- und Audioausgabe konfigurieren"              \
    Netzwerk       "Netzwerk-Karte und -Services einrichten"            \
    Fernbedienung  "Fernbedienung konfigurieren"                        \
    Kanalliste     "Kanalliste auswaehlen und aktivieren"               \
    Infodisplay    "Infodisplay konfigurieren"                          \
    Choose_Desktop "Desktop auswaehlen"                                 \
    PChanger       "(De)Aktivieren des Programmumschalters"             \
    Addons         "Addons managen (Internet Verbindung erforderlich)"  \
    VDR            "Das Menue verlassen und den VDR starten"            \
    Reboot         "Das System neu starten"                             3>&1 1>&2 2>&3 3>&- )
  OK_CANCEL=$?
  clear

  if (( $OK_CANCEL == 0 )); then
    OK_CANCEL_SUB=0
    case $SET_MENUITEM in
      AudioVideo_out) Menu_Audio_Video_out   ;;
       Fernbedienung) Menu_Fernbedienung     ;;
                   *) Run_Selected           ;;
    esac
  else
    echo "`date` Abbruch ohne VDR-Start..." >> $SETUPLOG
  fi
done
}

#####
Menu_Audio_Video_out()
{
while (( $OK_CANCEL_SUB == 0 ))
do
  SET_MENUITEM=$(dialog \
        --backtitle "$BACKTITLE"\
        --title "$TITLE"\
        --cancel-label "Zurueck" \
        --menu "\
      Steuerung mit:                     [   UP   ] [ DOWN ] \n\
      Zum Auswaehlen:                    <  OK  > \n\
      Zurueck zum Hauptmenu:             < Zurueck > "   $DIA_BOX_SIZE \
    Video_out      "Videoausgabe konfigurieren"                         \
    Monitor_Layout "Bildschirme konfigurieren"                          \
    Video_Details  "Video Dekodierung konfigurieren"                    \
    OSD_Skin       "OSD-Skin einstellen"                                \
    Audio          "Soundausgabe einrichten"                            3>&1 1>&2 2>&3 3>&- )
  OK_CANCEL_SUB=$?
  clear

  if (( $OK_CANCEL_SUB == 0 )); then
    Run_Selected
  fi
done
}

#####
Menu_Fernbedienung()
{
while (( $OK_CANCEL_SUB == 0 ))
do
  SET_MENUITEM=$(dialog \
        --backtitle "$BACKTITLE"\
        --title "$TITLE"\
        --cancel-label "Zurueck" \
        --menu "\
      Steuerung mit:                     [   UP   ] [ DOWN ] \n\
      Zum Auswaehlen:                    <  OK  > \n\
      Zurueck zum Hauptmenu:             < Zurueck > "   $DIA_BOX_SIZE \
    Fb-Receiver    "Empfaenger der Fernbedienung auswaehlen"            \
    Fernbedienung  "Fernbedienung (Sender) auswaehlen"                  \
    Erw_FB_Einst   "Erweiterte FB-Einstellungen"                        3>&1 1>&2 2>&3 3>&- )
  OK_CANCEL_SUB=$?
  clear

  if (( $OK_CANCEL_SUB == 0 )); then
    Run_Selected
  fi
done
}

#####
Run_Selected()
{
case $SET_MENUITEM in
      Video_in) Video_in_set   ;;
 Video_connect) Video_con_set  ;;
     Video_out) Video_out_set  ;;
Monitor_Layout) M_layout_set   ;;
 Video_Details) Video_detal_set;;
      OSD_Skin) OSD_skin_set   ;;
         Audio) Audioset       ;;
      Netzwerk) Netzwerkset    ;;
   Fb-Receiver) Fb_Receiverset ;;
 Fernbedienung) Fb_Controllset ;;
  Erw_FB_Einst) Adv_Fb_Config  ;;
    Kanalliste) Chlistset      ;;
   Infodisplay) Infodisplayset ;;
Choose_Desktop) Desktopset     ;;
      PChanger) PChangeset     ;;
        Addons) Addonsset      ;;
           VDR) VDR_Start      ;;
        Reboot) Show_Countdown; echo "`date` System rebooten..." >> $SETUPLOG; reboot ;;
esac
}

#####
Prepare_Setup()
{
echo "`date` -  start script: easyvdr-fixes-ubuntu"            >> $SETUPLOG
$SETUP/easyvdr-fixes-ubuntu
Build_Files
}

#####
Start_on_Term8()
{
#Prüfen ob Setup über Systemd gestartet wurde
systemctl is-active "easyvdr-setup-call.service" > /dev/null 2>&1
if [ $? -eq 0 ]; then
  echo "`date` Info: Setup wurde automatisch beim Reboot nach der Installation gestartet" >> $SETUPLOG
 
 for i in {1..10}
 do
    chvt 8
    (( $(fgconsole) == 8 )) && break
    sleep 1
    echo "$i"
 done

if test -d /local-repo/; then
    echo "deb file:/local-repo/ trusty main"     > /tmp/pre-sources.list
    echo "deb file:/local-repo/ trusty extras"  >> /tmp/pre-sources.list
    cp /etc/apt/sources.list  /tmp/sources.list
    cat /tmp/pre-sources.list /tmp/sources.list   > /etc/apt/sources.list
fi

if test -d /var/cache/apt-local-repo/; then
    echo "deb file:///var/cache/apt-local-repo ./"     > /tmp/pre-sources.list
    cp  /etc/apt/sources.list /tmp/sources.list
    cat /tmp/pre-sources.list /tmp/sources.list   > /etc/apt/sources.list
fi


    echo "linux-generic" hold | dpkg --set-selections 
    echo "linux-headers-generic" hold | dpkg --set-selections 
    echo "linux-image-generic" hold | dpkg --set-selections
    apt-key add /local-repo/pool/extras/uck-remaster.key  >/dev/null 2>&1

#    echo " `date` Starte apt-get update"     >> $SETUPLOG
#    debconf-apt-progress -- apt-get --yes update 2>&1

fi
}

#####
Finalize_Setup()
{
systemctl is-enabled "easyvdr-setup-call.service" > /dev/null 2>&1
if [ $? -eq 0 ]; then
 systemctl disable "easyvdr-setup-call.service" || true > /dev/null 2>&1
fi

echo "`date` Setup abschliessen:" >> $SETUPLOG
echo "`date` Setup: systemd Dienste aktivieren:" >> $SETUPLOG

EnableSystemd
sed -i -e "s|^\(ENABLED\)=.*|\1=\"yes\"|;" /etc/default/vdr
}

#####
Video_in_set()   { echo "`date` - start setup-script: easyvdr-config-video-in"          >> $SETUPLOG; $SETUP/easyvdr-config-video-in               $RUN_OPTION; i=0; }
Video_con_set()  { echo "`date` - start setup-script: easyvdr-connect-video-in"         >> $SETUPLOG; $SETUP/easyvdr-connect-video-in              $RUN_OPTION; i=0; }
Video_out_set()  { echo "`date` - start setup-script: easyvdr-config-video-out"         >> $SETUPLOG; $SETUP/easyvdr-config-video-out              $RUN_OPTION; i=0; }
M_layout_set()   { echo "`date` - start setup-script: easyvdr-config-monitor-layout"    >> $SETUPLOG; $SETUP/easyvdr-config-monitor-layout         $RUN_OPTION; i=0; }
Video_detal_set(){ echo "`date` - start setup-script: easyvdr-config-video-details"     >> $SETUPLOG; $SETUP/easyvdr-config-video-details          $RUN_OPTION; i=0; }
OSD_skin_set()   { echo "`date` - start setup-script: easyvdr-config-osd"               >> $SETUPLOG; $SETUP/easyvdr-config-osd                    $RUN_OPTION; i=0; }
Audioset()       { echo "`date` - start setup-script: easyvdr-config-audio"             >> $SETUPLOG; $SETUP/easyvdr-config-audio --config --quiet $RUN_OPTION; i=0; }
Fb_Receiverset() { echo "`date` - start setup-script: easyvdr-config-remote-receiver"   >> $SETUPLOG; $SETUP/easyvdr-config-remote-receiver        $RUN_OPTION; i=0; }
Fb_Controllset() { echo "`date` - start setup-script: easyvdr-config-remote-controller" >> $SETUPLOG; $SETUP/easyvdr-config-remote-controller      $RUN_OPTION; i=0; }
Netzwerkset()    { echo "`date` - start setup-script: easyvdr-config-network"           >> $SETUPLOG; $SETUP/easyvdr-config-network                $RUN_OPTION; i=0; }
Chlistset()      { echo "`date` - start setup-script: easyvdr-select-channellist"       >> $SETUPLOG; $SETUP/easyvdr-select-channellist            $RUN_OPTION; i=0; }
Infodisplayset() { echo "`date` - start setup-script: easyvdr-config-infodisplay"       >> $SETUPLOG; $SETUP/easyvdr-config-infodisplay            $RUN_OPTION; i=0; }
Desktopset()     { echo "`date` - start setup-script: easyvdr-choose-desktop"           >> $SETUPLOG; $SETUP/easyvdr-choose-desktop                $RUN_OPTION; i=0; }
PChangeset()     { echo "`date` - start setup-script: easyvdr-config-pchanger"          >> $SETUPLOG; $SETUP/easyvdr-config-pchanger               $RUN_OPTION; i=0; }
Addonsset()      { echo "`date` - start setup-script: easyvdr-config-addons"            >> $SETUPLOG; $SETUP/easyvdr-config-addons                 $RUN_OPTION; i=0; }
Adv_Fb_Config()  { echo "`date` - start setup-script: easyvdr-make-remote-mapping"      >> $SETUPLOG; $SETUP/easyvdr-make-remote-mapping           $RUN_OPTION; i=0; }


#####
VDR_Start()
{

MiniInfo " working " "$BACKTITLE" "\n\n\n \Zb\Z1   VDR wird gestartet"
OK_CANCEL=1; sleep 5

Get_Frontend_Class
 case $FRONTEND_CLASS in
      "USE_X11") chvt $XKEYB_TTY; echo "`date` Starte Desktop..."  >> $SETUPLOG
        chvt $XKEYB_TTY
        # X Berechtigung, Key löschen sonst läuft X / lightdm nicht richtig 
        if [ -f /home/$STANDARD_DESKTOP_USER/.Xauthority ];then
         rm /home/$STANDARD_DESKTOP_USER/.Xauthority >/dev/null 2>&1
        fi
        easyvdr-desktop start >/dev/null 2>&1 

        /usr/lib/vdr/easyvdr-set-monitor-layout > /dev/null 2>&1
        easyvdr-program-changer start;;

      "NON_X11") chvt $DKEYB_TTY;;
      "NON_FRE") chvt 1;;
 esac

echo "`date` Starte VDR remote Service..."      >> $SETUPLOG
easyvdr-remote start                               >/dev/null 2>&1
sleep 1
echo "`date` Starte VDR..."      >> $SETUPLOG
easyvdr-vdr start                               >/dev/null 2>&1
sleep 1
echo "`date` Starte Frontend..." >> $SETUPLOG
easyvdr-frontend start   >/dev/null 2>&1
clear

while true
  do
    (pidof vdr > /dev/null 2>&1) && break
    sleep 0.2
  done
 clear

}


#####
Stop_X_Windows()
{
#if [ $(check_x_running > /dev/null 2>&1) ]; then
if (check_x_running > /dev/null 2>&1); then
  VT_KONSOLE=$(fgconsole)         ## aktuell aktives Terminal
  easyvdr-program-changer stop >/dev/null 2>&1
  easyvdr-desktop stop  >/dev/null 2>&1
  chvt $VT_KONSOLE
fi
}

#####
Run_Main()
{
Detect_Intro_Menu
if (( $YESNO == 0 ))
  then
    HW_Detect_Install_Errorfree="false"
    while [ $HW_Detect_Install_Errorfree == "false" ]; do
      Run_HW_Detect
      Check_Install_Log
    done
    if [ $HW_Detect_Install_Errorfree == "exit" ]; then
	Canceled_Setup
	RET_STAT=1
    else
	Main
	Finalize_Setup
	Finished_Setup
    fi
  else
    Canceled_Setup
    RET_STAT=1
fi
}

#####
Finished_Setup()
{
sed -i '/"*easyvdr-setup-main"*/d' $SETUP_STATUS
echo "# `date` easyvdr-setup-main zuletzt ausgefuehrt" >> $SETUP_STATUS
sed -i '/Setup_main_finished"*/d' $SETUP_STATUS
echo "Setup_main_finished=\"true\"" >> $SETUP_STATUS
VDR_Start
}

#####
Canceled_Setup()
{
sed -i '/"*easyvdr-setup-main"*/d' $SETUP_STATUS
echo "# `date` easyvdr-setup-main zuletzt ausgefuehrt" >> $SETUP_STATUS
sed -i '/Setup_main_finished"*/d' $SETUP_STATUS
echo "Setup_main_finished=\"false\"" >> $SETUP_STATUS
}

#####
Get_Frontend_Class()
{
. $CFG_DIR/sysconfig
case $VDR_FRONTEND in
     "vdr-sxfe") FRONTEND_CLASS="USE_X11" ;;
         "xine") FRONTEND_CLASS="USE_X11" ;;
         "ENNA") FRONTEND_CLASS="USE_X11" ;;
         "KODI") FRONTEND_CLASS="USE_X11" ;;
 "Softhddevice") FRONTEND_CLASS="USE_X11" ;;
       "DVB-FF") FRONTEND_CLASS="NON_X11" ;;
     "DVBS2-FF") FRONTEND_CLASS="NON_X11" ;;
      "reelbox") FRONTEND_CLASS="NON_X11" ;;
       "PVR350") FRONTEND_CLASS="NON_X11" ;;
       "keines") FRONTEND_CLASS="NON_FRE" ;;
              *) FRONTEND_CLASS="NON_FRE" ;;
esac
}

######################################### main ####################################################
RET_STAT=1

Master_of_Desaster                    # check auf Admin-Rechte
if (( ROOT_STAT == 0 )); then
  RET_STAT=0
  case $RUN_OPTION in                 # Aufrufparameter auswerten
         "-f") Check_Console
               (( $CONSOLE_STAT == 0 )) &&  Menu || RET_STAT=1
               ;;
  "-progress") Build_Files
	       Run_Main
               ;;
            *) Run_On_Install
               if (( $RET_STAT == 0 )) 
                 then
                   Prepare_Setup
                   Start_on_Term8
                   Pre_Main
                   Run_Main
                 else
                   echo "Fehler! -- Pfusch nich dran rum!" >> $SETUPLOG
                   echo "Fehler! -- Pfusch nich dran rum!"; sleep 10
               fi
               ;;
  esac
fi
echo "`date` Zentrales Setup-Script bis zum Ende durchgelaufen, Return-Status=$RET_STAT" >> $SETUPLOG
exit $RET_STAT

