#!/bin/bash
#################################################
#Skript für Video / VDPAU / VAAPI Anpassungen
#Die easyvdr-frontend*.conf werden auch geaendert
#
#V 0.1  24.09.13 Bleifuss2
#V 0.2  27.11.13 Bleifuss2 
#V 0.2  29.12.13 change vaapi to va-api-glx Tipp von jones
#V 0.2  23.07.14 Bildschirmschoner deaktiviert
#V 0.5  09.06.15 Dialoge jetzt ohne radiolist by michel8
#V 0.6  05.01.16 Funktion Softhd Frontend setzen
#V 0.7  02.12.17 Systemd update & Bugfix

. /usr/lib/vdr/easyvdr-config-loader                   ## common defines
. /usr/lib/vdr/functions/easyvdr-functions-lib         ## common functions
. /usr/share/easyvdr/setup/easyvdr-setup-defines       ## setup only defines
. /usr/share/easyvdr/setup/easyvdr-setup-functions     ## setup only functions
. $SETUP/video-setup/easyvdr-video-lib
CONF_FILE=/etc/vdr/easyvdr/easyvdr-video-settings.conf
. $CONF_FILE

VIDEOLOG="$EASYVDR_LOGDIR/easyvdr-config-video-details.log"

TITLE=" Setup easyVDR $EASYVDR_VERSION "
BACKTITLE="Video Details"

InstallPackage ()
{
 #$1 Name der Pakets
 echo "" >> $APT_GET_LOG
 echo "===> ########################################################################################" >> $APT_GET_LOG
 echo "===> `date`: Install $1 ..." >> $APT_GET_LOG
 debconf-apt-progress --logfile $APT_GET_LOG -- apt-get --yes install $1
 AptStatus=$?
 echo "#############################################################################################" >> $APT_GET_LOG
 echo "" >> $APT_GET_LOG
 if [ $AptStatus -ne 0 ];then
  dialog --backtitle "$BACKTITLE" --no-cancel --pause "\n\
    $1 kann nicht installiert werden \n\n\
                            - Weiter - " $DIA_BOX4_SIZE $TIMEOUT
  clear
  exit
 fi
}

SetVaapi ()
{

 apt-get remove "easyvdr-softhdd easyvdr-x-depends vdr-plugin-softhddevice" >/dev/null 2>&1
 InstallPackage "easyvdr-x-depends easyvdr-softhdd-vaapi i965-va-driver gstreamer1.0-vaapi libvdpau-va-gl1 vdr-plugin-softhddevice-vaapi"

 echo "VAAPI gewaehlt" >>$VIDEOLOG
#sxfe Parameter
 CONF_FILE="$CFG_DIR/easyvdr-frontend-sxfe.conf"
 SetConfFileParameter "ACCELERATION" ""
# SetConfFileParameter "VIDEO_DEVICE" "--video=vaapi" 
 SetConfFileParameter "VIDEO_DEVICE" "--video=vaapi" 
 SetConfFileParameter "VIDEO_MISCELLANEOUS_1" ""

#Softhddevice Parameter
 CONF_FILE="$CFG_DIR/easyvdr-frontend-softhddevice.conf"
 SetConfFileParameter "FRONTEND_DISPLAY" "-d $FRONTEND_DISPLAY"
 SetConfFileParameter "ACCELERATION" ""
#va-api-glx
 SetConfFileParameter "VIDEO_DEVICE" "-v va-api"
}

SetVdpau ()
{

 apt-get remove "easyvdr-x-depends easyvdr-softhdd-vaapi i965-va-driver vdr-plugin-softhddevice-vaapi" >/dev/null 2>&1
 InstallPackage "easyvdr-softhdd easyvdr-x-depends vdr-plugin-softhddevice"

 echo "VDPAU gewaehlt" >>$VIDEOLOG
#sxfe Parameter
 CONF_FILE="$CFG_DIR/easyvdr-frontend-sxfe.conf"
 SetConfFileParameter "ACCELERATION" ""
 SetConfFileParameter "VIDEO_DEVICE" "--video=vdpau"
 SetConfFileParameter "VIDEO_MISCELLANEOUS_1" "--post tvtime:method=use_vo_driver"

#Softhddevice Parameter
 CONF_FILE="$CFG_DIR/easyvdr-frontend-softhddevice.conf"
 SetConfFileParameter "FRONTEND_DISPLAY" "-d $FRONTEND_DISPLAY"
 SetConfFileParameter "ACCELERATION" ""
 SetConfFileParameter "VIDEO_DEVICE" "-v vdpau"
}
###
# 1 Parameter -> Optimal, Befriedigend oder OSD
Set_Software_Dekodierung ()
{
 echo "xineliboutput auf Softwaredekodierung umstellen" >>$VIDEOLOG

 CONF_FILE="$CFG_DIR/easyvdr-frontend-sxfe.conf"
 SetConfFileParameter "VIDEO_DEVICE" ""

 local OK_CANCEL=1
 SEL=$(dialog \
     --backtitle "$BACKTITLE" \
     --title "$TITLE" \
     --ok-label " O.K. "\
     --menu "\n\
Video Decodierung waehlen.\nIm Zweifelsfall nacheinander testen" $DIA_BOX_SIZE \
"Optimal" "CPU > 2X2,5GHz oder nur SD TV" \
"Befriedigend" "CPU > 2.5GHz fuer HD" \
"OSD" "Qualitaet anpassen, Einst.->Plugins->Xineliboutput"  3>&1 1>&2 2>&3 3>&- )

 OK_CANCEL=$?
 clear
 case $SEL in
      Optimal)
      #Fast CPU
      echo "High: VIDEO_MISCELLANEOUS_1=--post \
 tvtime:enable=1,cheap_mode=1,pulldown=0,use_progressive_frame_flag=1" >>$VIDEOLOG
           SetConfFileParameter "VIDEO_MISCELLANEOUS_1" "--post \
 tvtime:enable=1,cheap_mode=1,pulldown=0,use_progressive_frame_flag=1"
      ;;
      Befriedigend)
      #Slow CPU
      echo "Low: VIDEO_MISCELLANEOUS_1=--post \
 tvtime:enable=1,method=Greedy2frame,cheap_mode=1,pulldown=0,use_progressive_frame_flag=1" >>$VIDEOLOG
           SetConfFileParameter "VIDEO_MISCELLANEOUS_1" "--post\
 tvtime:enable=1,method=Greedy2frame,cheap_mode=1,pulldown=0,use_progressive_frame_flag=1"
      ;;
      OSD)
      #OSD Setup
       echo "OSD: VIDEO_MISCELLANEOUS_1=--post tvtime:enable=1" >>$VIDEOLOG
       SetConfFileParameter "VIDEO_MISCELLANEOUS_1" "--post tvtime:enable=1"
      ;;
 esac
}
###
Select_Vaapi_Vdpau_Softw ()
{
local OK_CANCEL=1
 SEL=$(dialog \
     --backtitle "$BACKTITLE" \
     --title "$TITLE" \
     --ok-label " O.K. "\
     --menu "\n\
 Video Decodierung waehlen.\n Im Zweifelsfall nacheinander testen" $DIA_BOX_SIZE\
 "${TEXT_ARRAY[@]}" 3>&1 1>&2 2>&3 3>&- )
 OK_CANCEL=$?
 clear
 case $SEL in
      VDPAU)
         SetVdpau
      ;;
      VAAPI)
         SetVaapi
      ;;
      Software-Dekodierung)
         Set_Frontend_sxfe
         Set_Software_Dekodierung
     ;;
 esac
}
###
Set_Frontend_sxfe ()
{
 SetSysconfig VDR_FRONTEND  vdr-sxfe                     # schreiben des ausgewaehlten Frontend in die sysconfig
 /usr/lib/vdr/easyvdr-set-settings "frontend"            # setze Parameter je nach frontend
 echo "set frontend vdr-sxfe" >>$VIDEOLOG
}
###
Set_Frontend_softhddevice ()
{
 SetSysconfig VDR_FRONTEND  Softhddevice                 # schreiben des ausgewaehlten Frontend in die sysconfig
 /usr/lib/vdr/easyvdr-set-settings "frontend"            # setze Parameter je nach frontend 
 echo "set frontend softhddevice" >>$VIDEOLOG
}


###############################################################################
echo "$(date) Video-config-details gestartet" >>$VIDEOLOG

#### Frontend Prüfen
Get_Frontend_Class

# X Berechtigung, Key löschen sonst läuft X / lightdm nicht richtig 
rm_xauthority

if [ $FRONTEND_CLASS == "USE_X11" ]; then
 #Terminal merken
 VT_KONSOLE_OLD=$(fgconsole)         # aktuell aktives Terminal

 # stop X
 if ( check_x_running ) >/dev/null 2>&1 ; then
  easyvdr-desktop stop >/dev/null 2>&1 ; sleep 1
 fi

 PID=$(pgrep "easyvdr-runfron" )
 if [ $? -eq 0 ]; then
  easyvdr-frontend stop;sleep 1
 fi
 chvt $VT_KONSOLE_OLD               # zurueck zur aufrufenden Konsole
 echo "startx for vdpau/vaapi detection" >>$VIDEOLOG

 dialog --backtitle "$BACKTITLE" --no-cancel --pause "\n\
           Als naechstes wird VDPAU und VAAPI gesucht\n\n\
                              - Weiter - " $DIA_BOX4_SIZE $TIMEOUT

 clear

 startx  "$SETUP/video-setup/x-hardware-detection-check-vdpau-vaapi"  --  $PRIMARY_DISPLAY >/dev/null 2>&1

###
#Konfiguration einlesen
 . $CONF_FILE
#Default Frontend setzen
 Set_Frontend_softhddevice

 chvt $VT_KONSOLE_OLD               # zurueck zur aufrufenden Konsole

###############################################################################
## Testen ob VDPAU & VAAPI
 if [ $VDPAU == "yes" ] && [ $VAAPI == "yes" ];then
  #VDPAU + VAAPI
  echo "Die Grafikkarte unterstuetzt VDPAU und VAAPI" >>$VIDEOLOG
 
  TEXT_ARRAY[0]="VDPAU"; TEXT_ARRAY[1]="Optimal fuer Nvidia-Karten"
  TEXT_ARRAY[2]="VAAPI"; TEXT_ARRAY[3]="Fuer Intel AMD usw." 
  TEXT_ARRAY[4]="Software-Dekodierung"; TEXT_ARRAY[5]="Wenn VDPAU und VAAPI nicht funktionieren"
  Select_Vaapi_Vdpau_Softw
 else
  if [ $VDPAU == "yes" ];then
   #VDPAU
   TEXT_ARRAY[0]="VDPAU"; TEXT_ARRAY[1]="Optimal fuer Nvidia-Karten"
   TEXT_ARRAY[2]="Software-Dekodierung"; TEXT_ARRAY[3]="Wenn VDPAU und VAAPI nicht funktionieren"
   Select_Vaapi_Vdpau_Softw
  else
   if [ $VAAPI == "yes" ];then
    #VAAPI
    TEXT_ARRAY[0]="VAAPI"; TEXT_ARRAY[1]="Fuer Intel AMD usw." 
    TEXT_ARRAY[2]="Software-Dekodierung"; TEXT_ARRAY[3]="Wenn VDPAU und VAAPI nicht funktionieren"
    Select_Vaapi_Vdpau_Softw
   else
   #Software

    dialog --backtitle "$BACKTITLE" --no-cancel --pause "\n\
           Das System unterstuetzt nur Software Dekodierung.\n\
  Software Dekodierung funktioniert nur mit dem Xineliboutput Plugin.\n\n\
                              - Weiter - " $DIA_BOX4_SIZE 30
    Set_Frontend_sxfe
    Set_Software_Dekodierung
   fi
  fi
 fi
else
 if [ "$Video_details_configured"  == "true" ];then
    dialog --backtitle "$BACKTITLE" --no-cancel --pause "\n\
           Diese Option ist nur mir einem X11 Frontend verfuegbar. \n\n\
                              - Weiter - " $DIA_BOX4_SIZE 30
 fi
fi

##
WriteStatus easyvdr-config-video-details Video_details_configured
