#!/bin/bash
#
#-------------------------------------------
# Dieses Skript installiert den korrekten NVidiatreiber
#-------------------------------------------
# Autor: Sinai for easyVDR 2.0
#-------------------------------------------
# Hinweis: 
#-------------------------------------------
# Version 1.0 by Sinai             # initial version
#             adding remove driver bleifuss
# Version 1.3 new DriverVersions for V3.0 by michel8
# -------------------------------------------
#
################################################
#defines
. /usr/lib/vdr/easyvdr-config-loader
. /usr/lib/vdr/functions/easyvdr-functions-lib
. /usr/share/easyvdr/setup/easyvdr-setup-defines

VERSION="1.3"
TITLE=" Setup fuer easyVDR $EASYVDR_VERSION - NVidia-Treiber "
BACK_TITLE=" Treiberinstallation fuer easyVDR - Version $VERSION "


################## Funktionen ################################################

#####
Intro_Menu()
{
VGA=$(lspci | grep VGA | awk -F: '{ print $3 }')
dialog --backtitle "$BACKTITLE"\
       --title " $TITLE "\
       --msgbox "\n\n\n\
        Folgende Grafikkarte wurde vom System erkennt.\n\n
        $VGA\n\n
        Bitte waehlen Sie einen passenden Treiber\n
        auf der naechsten Seite aus.\n\n\n"\
        $DIA_BOX2_SIZE
clear
}
#####
Install_Nvidia_Driver()
{

 dpkg -l | grep $1 | grep ii  >/dev/null 2>&1
 if [ $? -ne 0 ];then
  apt-get remove -y easyvdr-nvidia-latest
  rm -rf /var/lib/dpkg/info/nvidia-*.postrm  >/dev/null 2>&1
  apt-get remove -y nvidia*  >/dev/null 2>&1
  rm -rf /var/lib/dpkg/info/nvidia-*.list  >/dev/null 2>&1
  apt-get -y install easyvdr-video-out-nvidia $1
  apt-get -y install -f
  modprobe nvidia
 fi
}

#####
Available_Drivers()
{

CURRENT_DRIVER=$(dpkg -l | grep  -i ii | grep "nvidia" | grep "binary" | cut -d" " -f2-5)

if [ X"$CURRENT_DRIVER" != "X" ];then 
 CURRENT_DRIVER="Aktueller Treiber:    $CURRENT_DRIVER\n"
else
 CURRENT_DRIVER=" "
fi

OK_CANCEL=1
SEL_DRIVER=$(dialog\
    --backtitle "$BACKTITLE"\
    --title " $TITLE "\
    --colors\
    --cancel-label " Abbrechen " \
    --default-item "2"\
    --menu  "\n\
    Welcher Treiber soll fuer die NVidiakarte installiert werden?\n\n\
    $CURRENT_DRIVER\n\
    Markierten Treiber Installieren mit < OK >\n\
    Beenden ohne Installation mit < Abbrechen >"  $DIA_BOX_SIZE\
    "1" "NVidia-304 - fuer alte 8000/9000 (OnBoard-) Grafik-Chips"\
    "2" "NVidia 340 - (oder neuerer) Stable aus dem Ubuntu ppa"\
    "3" "NVidia-370 - (oder neuerer) Treiber aus dem easyvdr ppa"\
    "4" "NVidia-38X - für die neuen 10XX Karten, aus dem easyvdr ppa"\
  3>&1 1>&2 2>&3 3>&- )
OK_CANCEL=$?
clear

if (($OK_CANCEL == 0)); then
  case $SEL_DRIVER in
     1) echo "Installiere Treiber 304.117"
        Install_Nvidia_Driver "nvidia-304";;
     2) echo "Installiere Treiber 340 oder neuer aus dem Ubuntu ppa"
        Install_Nvidia_Driver "nvidia-331-updates";;
     3) echo "Installiere aktuellen Treiber aus dem easyvdr ppa"
        Install_Nvidia_Driver " nvidia-370" ;;
     4) echo "Installiere aktuellen Treiber aus dem easyvdr ppa"
        Install_Nvidia_Driver "easyvdr-nvidia-latest" ;;
  esac
fi
return $OK_CANCEL

}

###################### main ########################## 

Intro_Menu
if (($? == 0)); then
  Available_Drivers
fi

