#!/bin/bash
#16.04.14  V 0.1 Bleifuss 

. /usr/lib/vdr/easyvdr-config-loader                   ## common defines
. /usr/lib/vdr/functions/easyvdr-functions-lib         ## common functions
. /usr/share/easyvdr/setup/easyvdr-setup-defines       ## setup only defines
. /usr/share/easyvdr/setup/easyvdr-setup-functions     ## setup only functions


LOGGER=" logger -t easyvdr-ubuntu-driver-setup"

TITLE=" Setup fuer easyVDR $EASYVDR_VERSION  "
BACKTITLE=" Proprietaere Treiber installieren " 


DIA_BOX4_SIZE="14 75"

CONNECTOR=$1
  dialog --backtitle "$BACKTITLE" --no-cancel --yesno "\n\
          Treiber fuer nicht unterstuetze Hardware suchen.\n\
        Bitte im Forum Posten welche Hardware verwendet wird.\n\
            Da hier der Easyvdr Bereich verlassen wird\n\
              ist nicht sicher ob alles funktioniert.\n\
  In dem nachfolgenden Dialog NUR die Treiber einstellungen anpassen.\n\
                 Die Ubuntu Treiber installation starten?  \n\n" $DIA_BOX4_SIZE
 clear

 if [ $? -ne "0" ]; then
  exit
 fi

############## X beenden
#Terminal merken
VT_KONSOLE_OLD=$(fgconsole)         # aktuell aktives Terminal

PID=$(pgrep "easyvdr-runvdr" )
if [ $? -eq 0 ]; then
 stop easyvdr-vdr;sleep 1
fi

PID=$(pgrep "easyvdr-runfron" )
if [ $? -eq 0 ]; then
 stop easyvdr-frontend;sleep 1
fi

#Stop X
if ( check_x_running ) >/dev/null 2>&1 ; then
 stop easyvdr-desktop >/dev/null 2>&1 ; sleep 1
fi

chvt $VT_KONSOLE_OLD               # zurueck zur aufrufenden Konsole
###############


 echo "" >> $APT_GET_LOG
 echo "===> ########################################################################################" >> $APT_GET_LOG
 echo "===> `date`: Install software-properties-gtk ..." >> $APT_GET_LOG
 debconf-apt-progress --logfile $APT_GET_LOG -- apt-get --yes install software-properties-gtk
 AptStatus=$?
 echo "#############################################################################################" >> $APT_GET_LOG
 echo "" >> $APT_GET_LOG
 if [ $AptStatus -ne 0 ];then
  dialog --backtitle "$BACKTITLE" --title "$TITLE" --no-cancel --pause "\n\
    Ubuntu Treiber Setup kann nicht installiert werden \n\n\
                            - Weiter - " $DIA_BOX4_SIZE $TIMEOUT
  clear
  exit
 fi


start easyvdr-desktop  >/dev/null 2>&1
sleep 1
DISPLAY=:0  software-properties-gtk  --no-update  --open-tab=4  >/dev/null 2>&1

#Warten bis das Programm beendet wird
while ( check_x_running ) >/dev/null 2>&1
do
 sleep 1
 if ( ! pidof software-properties-gtk ) >/dev/null 2>&1 ; then
  #Stop X
  if ( check_x_running ) >/dev/null 2>&1 ; then
   stop easyvdr-desktop >/dev/null 2>&1 ; 
  fi
 fi
done
chvt $VT_KONSOLE_OLD               # zurueck zur aufrufenden Konsole
#startx  "'software-properties-gtk  --no-update  --open-tab=4'"  --  $PRIMARY_DISPLAY >/dev/null 2>&1



