#!/bin/bash
#
#
#  v0.1     29.12.12 Captain_Beefheart
#  v0.1.1   05.07.13 C.B.  # small fix - checks whether entry exists
#
#
#################################################

###### definitions #####

IDENTS[0]="# / was on"
IDENTS[1]="# /media/easyvdr01 was on"

DELFILE="/tmp/.noat_delfile"
INSFILE="/tmp/.noat_insfile"
ORGFILE="/etc/fstab"

NEWOPT="noatime"

#####
Do_Patch()
{
CUR_IDENT="$1"

F_STRING=$(grep -A1 "$CUR_IDENT" $ORGFILE | grep -v "$CUR_IDENT")
DEL_PA_UUID=$(echo "$F_STRING" | cut -d/ -f1)
F_ARRAY=($F_STRING)

PA_UUID=${F_ARRAY[0]}
M_POINT=${F_ARRAY[1]}
F_SYSTE=${F_ARRAY[2]}
OPTIONS=${F_ARRAY[3]}
No_1=${F_ARRAY[4]}
No_2=${F_ARRAY[5]}

echo "$OPTIONS" | grep -q "$NEWOPT" || OPTIONS="$NEWOPT,$OPTIONS"

echo "$DEL_PA_UUID/"                                        > $DELFILE
echo "$PA_UUID  $M_POINT  $F_SYSTE  $OPTIONS  $No_1  $No_2" > $INSFILE

tripatch -q -d/ $DELFILE $INSFILE $ORGFILE
rm $DELFILE; rm $INSFILE
}

##########  main  ##############

for IDENT in "${IDENTS[@]}"
  do
    if grep -q "$IDENT" $ORGFILE; then
      Do_Patch "$IDENT"
    fi
  done

