#!/bin/bash
#
#
#   1st start  version 0.4 
#
#  Captain_Beefheart
#
#  31.03.12 easyvdr-openbox -> easyvdr-desktop; removed inputlirc
#  v 0.4   removed unused insert  05.01.13  C.B.
#  v 0.4.1 added logrotate        02.02.13  C.B.
#  v 0.4.2 adde  MiniInfo         07.04.13  C.B.
#  v 0.4.3 systemd update         26.07.18 Bleifuss
############################

. /usr/share/easyvdr/setup/easyvdr-setup-functions

BACKTITLE=" 1st-start fuer easyVDR"
TITLE=" Erneutes Setup starten "

######## System auf Anfang setzen

INFO_TXT="\n\
        VDR wird rebooted \n\
   und das Setup erneut gestartet.\n\n\
        Dieses dauert etwas.\n\
           !don't panic!"

MiniInfo "$TITLE" "$BACKTITLE" "$INFO_TXT"
sleep 5; clear

sed -i -e "s|^\(ENABLED\)=.*|\1=\"no\"|;" /etc/default/vdr

logrotate -f /etc/logrotate.conf 

rm -f $EASYVDR_LOGDIR/setup.state
rm -f /var/log/syslog


# easyvdr Dienste deaktivieren
DisableSystemd
####################
# Setup Service aktivieren
systemctl enable "/etc/systemd/easyvdr/easyvdr-setup-call.service" || true > /dev/null 2>&1


sleep 1
clear
sleep 1
reboot

