#!/bin/bash
#
# Konfiguration der Infodisplays
#
#  michel8
#  v0.1
#
#  v0.4   08.10.11   komplette Umstellung auf hw-detect  Captain_Beefheart
#  v0.5   15.02.12   SurfaceCleanerZ
#  v0.6   25.01.13   new defines  C.B.
#
#################################################

################################# defines ##########################################

. /usr/lib/vdr/easyvdr-config-loader
. /usr/lib/vdr/functions/easyvdr-functions-lib
. /usr/share/easyvdr/setup/easyvdr-setup-defines
. /usr/share/easyvdr/setup/easyvdr-setup-functions

TITLE="  Setup fuer easyVDR $EASYVDR_VERSION - Infodisplays "
TITLE2=" Neues Infodisplay installieren "
BACKTITLE=" Setup der Infodisplays"

############################### functions ##########################################

#####
New_Display()
{
dialog --backtitle "$BACKTITLE"\
       --title "$TITLE2"\
       --defaultno\
       --yes-label " neu installieren "\
       --no-label " abbrechen "\
       --yesno "\n\n\
                           !!ACHTUNG!! \n\n\
               Wenn Sie  \"neues Infodisplay installieren\"\n\
              auswaehlen, wird Ihre vorherige Konfiguration\n\
                  unwiederbringlich ueberschrieben!" $DIA_BOX2_SIZE
YES_NO=$?
clear
return $YES_NO
}

#####
Reset_Sysconfig()
{
SetSysconfig LCD keins
SetSysconfig START_GRAPHTFT no
}

#####
Run_Auto()
{
$DETECT/easyvdr-detect -Displ
}

#####
Get_Setup_Stat()
{
USE_CNF_FILE=$( grep Displ_config $SETUP_STATUS | cut -d" " -f3 )
}

#####
Configure_Display()
{
for CNF_FILE in $USE_CNF_FILE  
  do
    [ -f $HW_SETUP_SP/$LIB_NMK_$CNF_FILE ] &&  $HW_SETUP_SP/$LIB_NMK_$CNF_FILE
  done
}

#####
Write_Status()  ##  Setup.State schreiben ##
{
sed -i '/"*easyvdr-config-infodisplay"*/d' $SETUP_STATUS
echo "# `date` easyvdr-config-infodisplay zuletzt ausgefuehrt" >> $SETUP_STATUS
sed -i '/Infodisplay_configured"*/d' $SETUP_STATUS
echo "Infodisplay_configured=\"true\"" >> $SETUP_STATUS
}

######################################### main ####################################################

FORCE_FLAG=$1

case $FORCE_FLAG in
      -f)   New_Display
            if (( $? == 0 )); then
              Reset_Sysconfig
              Run_Auto
            fi
            Get_Setup_Stat
            Configure_Display;;
       *)   log --silent "$SETUP/easyvdr-config-infodisplay wird gestartet..."
            Get_Setup_Stat
            Configure_Display;;
esac
Write_Status

