#!/bin/bash
#
#  Netzwerkkonfiguration fuer easyvdr
#
#  v.0.1  michel8
#  v.0.4  added nfs    28.04.11  Captain_Beefheart
#  v.0.5  new defines  25.01.13  C.B.
#  v.0.6  get NM-Data  14.04.14  michel8
#  v.0.7  no echo      20.03.15  michel8
#  v.1.0  Use NM       01.03.16  michel8
#  v.1.1  no Timeout   19.04.16  michel8
#  v.1.2  OSD-Help     30.04.16  michel8
#############################################################################


############### defines #####################################################

. /usr/lib/vdr/easyvdr-config-loader
. /usr/lib/vdr/functions/easyvdr-functions-lib
. /usr/share/easyvdr/setup/easyvdr-setup-defines
. /usr/share/easyvdr/setup/easyvdr-setup-functions

HELP_FILE="$CFG_DIR/plugins/setup/help/nfs_access.hlp"


TITLE=" Setup fuer easyVDR $EASYVDR_VERSION - Netzwerk "
BACKTITLE=" Konfiguration des Netzwerkes"

############################### functions ###################################

Get_Options()
{
case $RUN_OPTION in
        -f) run="all"  ;;
         *) run="auto" ;;
esac
}

#####
Intro_Menu()
{
dialog --backtitle "$BACKTITLE"\
       --title "$TITLE"\
       --no-label " Auto "\
       --yes-label " Setup "\
       --defaultno \
       --yesno "\n\n\
                        Setup fuer easyVDR \n\n\
            Im folgendem koennen Sie Einstellungen fuer\n\
         das Netzwerk und Funktionen ueber Netzwerk vornehmen.\n\
    Um die Einstellungen aus der Syteminstallation zu uebernehmen\n\
           druecken Sie \"Auto\" ... oder warten einfach ;-)" $DIA_BOX2_SIZE
YES_NO=$?
clear
}

#####
Menu()
{
OK_CANCEL=0
while (( ! $OK_CANCEL ))
  do
    # im Dialog über Aktuellen Status informieren
    . $SETUP_STATUS
    [[ "$Net_Basic_done"  == "true" ]] && NET_STAT="(Done)" || NET_STAT="      "
    [[ "$Net_Stream_done" == "true" ]] && STR_STAT="(Done)" || STR_STAT="      "
    [[ "$Net_Remote_done" == "true" ]] && REM_STAT="(Done)" || REM_STAT="      "
    [[ "$Net_Samba_done"  == "true" ]] && SMB_STAT="(Done)" || SMB_STAT="      "
    [[ "$Net_FTP_done"    == "true" ]] && FTP_STAT="(Done)" || FTP_STAT="      "
    [[ "$Net_NFS_done"    == "true" ]] && NFS_STAT="(Done)" || NFS_STAT="      "
    [[ "$Net_Server_done" == "true" ]] && SRV_STAT="(Done)" || SRV_STAT="      "

    SEL_NETCONF=$(dialog \
          --backtitle "$BACKTITLE"\
          --title "$TITLE"\
          --cancel-label " Fertig "\
          --menu "\n\
          Steuerung mit      [   UP   ] [ DOWN ] \n\
          Zum Auswaehlen     <   OK   > \n\
          Fertig?  dann      < Fertig > "  $DIA_BOX_SIZE\
      Netzwerk    "$NET_STAT Netzwerk-Anschluss und ext. Zugriff einrichten"      \
      Fernzugriff "$REM_STAT Fernzugr. und zus. Dienste des VDR (de)aktivieren"   \
      Samba       "$SMB_STAT Samba konfigurieren"       \
      Pro-FTP     "$FTP_STAT FTP-Server konfigurieren"  \
      NFS         "$NFS_STAT Nfs konfigurieren"         \
      ExtServer   "$SRV_STAT Weitere Serverlocations einstellen" 3>&1 1>&2 2>&3)
    OK_CANCEL=$?
    clear

    if (( ! $OK_CANCEL )); then
      Run_Selected
    fi
  done
}

#####
Run_Selected()
{
## Ausgewaehlte Funktion ausführen
case $SEL_NETCONF in
      Netzwerk) if [[ $run == "all" ]]
                  then
                    Remote_Warning; (( $? == 0 )) && Run_Network
                  else
                    Run_Network
                fi ;;
   Fernzugriff) Run_RemoteAccess ;;
         Samba) Run_Samba ;;
       Pro-FTP) Run_FTP   ;;
           NFS) Run_NFS   ;;
     ExtServer) Run_Server ;;
esac
}

#####
Remote_Warning()
{
dialog --backtitle "$BACKTITLE"\
       --title "$TITLE"\
       --defaultno\
       --yesno "\n\n\
                           !!ACHTUNG!! \n\n\
           Die Konfiguration des Netzwerkes nicht ueber\n\
                  eine Remote-Verbindung aufrufen! \n\n\
         !Schneiden Sie nicht den Ast ab, auf dem Sie sitzen! ;-) \n\n\
                Bestaetigen Sie das Sie nicht ueber\n\
                  eine Remote-Verbindung arbeiten! " $DIA_BOX2_SIZE
YES_NO=$?
clear
return $YES_NO
}

#####
Write_Status()
{
if [[ "$Net_NFS_done" != "true"  ]]; then
    echo " "									 > $HELP_FILE
    echo "Die Einstellungen und Freigaben fuer NFS koennen nur "		>> $HELP_FILE
    echo "im Setup vom Toolmenu vorgenommen werden. "				>> $HELP_FILE
    echo " "									>> $HELP_FILE
    echo "Im Setup vom OSD kann NFS nur aktiviert oder deaktiviert werden."	>> $HELP_FILE
    echo " "									>> $HELP_FILE
    echo "Bisher wurde NFS im Setup vom Toolmenu nicht konfiguriert..."		>> $HELP_FILE
fi
sed -i '/"*easyvdr-config-network"*/d' $SETUP_STATUS
echo "# `date` easyvdr-config-network zuletzt ausgefuehrt" >> $SETUP_STATUS
sed -i '/Network_configured"*/d' $SETUP_STATUS
echo "Network_configured=\"true\"" >> $SETUP_STATUS
}


############# main runs ###############################################
# Netzwerk und Services einrichten

Run_Network() # Netzwerk  einrichten und konfigurieren.
{
$SETUP/easyvdr-config-netbasic $run
sed -i '/Net_Basic_done"*/d' $SETUP_STATUS
echo "Net_Basic_done=\"true\"" >> $SETUP_STATUS
}

#####
Run_RemoteAccess()  # Fernzugriff und andere Dienste konfigurieren
{
$SETUP/easyvdr-set-remote-services
sed -i '/Net_Remote_done"*/d' $SETUP_STATUS
echo "Net_Remote_done=\"true\"" >> $SETUP_STATUS
}

#####
Run_Samba()  # Samba konfigurieren
{
$SETUP/easyvdr-config-samba
sed -i '/Net_Samba_done"*/d' $SETUP_STATUS
echo "Net_Samba_done=\"true\"" >> $SETUP_STATUS
}

#####
Run_FTP()  # Pro-FTP Server konfigurieren
{
$SETUP/easyvdr-config-ftp
sed -i '/Net_FTP_done"*/d' $SETUP_STATUS
echo "Net_FTP_done=\"true\"" >> $SETUP_STATUS
}

#####
Run_NFS()
{
$SETUP/easyvdr-config-nfs
sed -i '/Net_NFS_done"*/d' $SETUP_STATUS
echo "Net_NFS_done=\"true\"" >> $SETUP_STATUS
}

#####
Run_Server()  # Server-IPs einstellen
{
$SETUP/easyvdr-set-server-ip
sed -i '/Net_Server_done"*/d' $SETUP_STATUS
echo "Net_Server_done=\"true\"" >> $SETUP_STATUS
}

############################# main #################################################

RUN_OPTION=$1
Get_Options

if [[ $run == "all"  ]]
  then
    Menu
  else
    Intro_Menu
    if (( $YES_NO == 0 ))
      then
        run="all"
        Menu
      else
        Run_Network
    fi
fi
Write_Status

