#!/bin/bash
#30.10.13  V 0.2 Bleifuss 
#10.11.13  V 0.2 added x-hardware-detection-check-display-resolution
#16.12.13  V 0.2 added ff/headless support
#16.01.14  V 0.3 added graphtft
#13.02.14  V 0.3 added scale format 
#27.03.14  V 0.3 added autostart video-details
#11.04.14  V 0.3 remove aspect ratio skaling 
#08.06.15  V 0.5 Dialoge jetzt ohne radiolist by michel8
#22.07.15  V 0.5 Ausgabegerätprüfung Dialog eingebaut
#14.09.17  V 0.6 Systemd update
#08.01.19  v 0.6 Anpassung Intel Erkennung

. /usr/lib/vdr/easyvdr-config-loader                   ## common defines
. /usr/lib/vdr/functions/easyvdr-functions-lib         ## common functions
. /usr/share/easyvdr/setup/easyvdr-setup-defines       ## setup only defines
. /usr/share/easyvdr/setup/easyvdr-setup-functions     ## setup only functions
. $SETUP/video-setup/easyvdr-video-lib
CONF_FILE=/etc/vdr/easyvdr/easyvdr-video-settings.conf
. $CONF_FILE
GRAPHTFT_XORG_CONF=$SETUP/default_settings/xorg-conf-graphtft.default
DEFAULT_XORG_CONF=$SETUP/default_settings/xorg.conf
CHECK_CONNECTED_DISPLAY_XORG_CONF=$SETUP/default_settings/xorg-check_connected_display.conf
X_TEST_FILE=/tmp/easyvdr_x
#Prüfen ob eine xorg.conf vorhanden ist
if [ ! -e $DEFAULT_XORG_CONF ];then
 #Es gibt keine mitgelieferte, minimale xorg.conf verwenden.
 cp $SETUP/default_settings/xorg.conf_default $SETUP/default_settings/xorg.conf
fi
if [ ! -e $CHECK_CONNECTED_DISPLAY_XORG_CONF ];then
 #Es gibt keine mitgelieferte Check Display xorg.conf, minimale xorg.conf verwenden.
 cp $SETUP/default_settings/xorg.conf_default $CHECK_CONNECTED_DISPLAY_XORG_CONF
fi
#################### lightdm aktivieren
if [ ! -f "/etc/systemd/system/display-manager.service" ] ;then
 ln -s  /lib/systemd/system/lightdm.service  /etc/systemd/system/display-manager.service
 systemctl daemon-reload
fi


LOGGER=" logger -t easyvdr-config-monitor-layout"

TITLE=" Setup fuer easyVDR $EASYVDR_VERSION  "
BACKTITLE=" Monitor Layout waehlen " 
START_VIDEO_DETAILS="false"

SET_NVIDIA_BusID()
{
 ######################### Bus ID eintragen #############################
 NVIDIA_BUSID=$( lspci | grep VGA | grep NVIDIA | cut -d " " -f1)
 NVIDIA_BUSID=$(echo $NVIDIA_BUSID | cut -d "." -f1):$(echo $NVIDIA_BUSID | cut -d "." -f2)
 cat /etc/X11/xorg.conf | sed -e s/"#   NVIDIA_BUS_ID"/"   BusID  "/g > /tmp/xorg.tmp
 cat /tmp/xorg.tmp | sed -e s/"PCI_XXXX"/"PCI:$NVIDIA_BUSID"/g > /etc/X11/xorg.conf
}

No_Resolution ()
{
local CONNECTOR=$1
  dialog --backtitle "$BACKTITLE" --no-cancel --pause "\n\
             Der Bildschirm an der Schnittstelle $CONNECTOR \n\
   hat keine passende Aufloesung, es wird der X11 Auto Modus verwendet.\n\n\
                               - Weiter - " $DIA_BOX4_SIZE 60
  clear
}
#An welchem Bildschirm soll der VDR angezeigt werden?
VDR_Screen_Checkbox()
{
if [ $(echo $DISPLAY_CONNECTOR1 | grep -c "HDMI") != 0 ]; then
    DEF_ITEM="$DISPLAY_CONNECTOR1"
elif [ $(echo $DISPLAY_CONNECTOR2 | grep -c "HDMI") != 0 ]; then
    DEF_ITEM="$DISPLAY_CONNECTOR2"
elif [ $(echo $DISPLAY_CONNECTOR3 | grep -c "HDMI") != 0 ]; then
    DEF_ITEM="$DISPLAY_CONNECTOR3"
else
    DEF_ITEM="$DISPLAY_CONNECTOR1"
fi

local OK_CANCEL=1
SEL_CONNECTOR=$(dialog \
     --backtitle "$BACKTITLE" \
     --title "$TITLE" \
     --default-item "$DEF_ITEM" \
     --ok-label " O.K. "\
     --menu "\n\
An welchem Grafikkarten Ausgang soll das VDR Bild ausgegeben werden? "  $DIA_BOX_SIZE\
      "$DISPLAY_CONNECTOR1"          " Anschluss " \
      "$DISPLAY_CONNECTOR2"          " Anschluss " \
      "$DISPLAY_CONNECTOR3"          " Anschluss "  3>&1 1>&2 2>&3 3>&- )
OK_CANCEL=$?
clear

case $SEL_CONNECTOR in
      $DISPLAY_CONNECTOR1) VDR_SCREEN_CONNECTOR=$DISPLAY_CONNECTOR1 ;;
      $DISPLAY_CONNECTOR2) VDR_SCREEN_CONNECTOR=$DISPLAY_CONNECTOR2 ;;
      $DISPLAY_CONNECTOR3) VDR_SCREEN_CONNECTOR=$DISPLAY_CONNECTOR3 ;;
esac

SetConfFileParameter VDR_SCREEN_CONNECTOR $VDR_SCREEN_CONNECTOR
}
################################################################################
# Fuer was soll der 2 Anschluss verwendet werden?
VDR_2_Screen_Connector_Checkbox()
{
VDR_CLONE_CONNECTOR="none"
VDR_GRAPHTFT_CONNECTOR="none"
SECONDARY_DESKTOP_CONNECTOR="none"

CONNECTOR1=$DISPLAY_CONNECTOR1

if [ $VDR_SCREEN_CONNECTOR == $DISPLAY_CONNECTOR1 ];then
 CONNECTOR1=$DISPLAY_CONNECTOR2
else
 CONNECTOR1=$DISPLAY_CONNECTOR1
fi

local OK_CANCEL=1
SEL_CONNECTOR=$(dialog \
     --backtitle "$BACKTITLE" \
     --title "$TITLE" \
     --ok-label " O.K. "\
     --default-item "NONE" \
     --menu "\n\
Was soll der Bildschirm am Anschluss $CONNECTOR1 anzeigen? "  $DIA_BOX_SIZE\
      "CLONE"    "Kopie vom TV Bild" \
      "GRAPHTFT" "GRAPHTFT Plugin" \
      "NONE"     "nichts" \
      "DESKTOP"  "Desktop, nur fuer Experten"   3>&1 1>&2 2>&3 3>&- )
OK_CANCEL=$?
clear

case $SEL_CONNECTOR in
      CLONE) 
         VDR_CLONE_CONNECTOR=$CONNECTOR1
         MONITOR_LAYOUT=CLONE
         SetConfFileParameter VDR_CLONE_CONNECTOR $CONNECTOR1
      ;;
      GRAPHTFT)
         VDR_GRAPHTFT_CONNECTOR=$CONNECTOR1
         MONITOR_LAYOUT=GRAPHTFT
         SetConfFileParameter VDR_GRAPHTFT_CONNECTOR $CONNECTOR1
      ;;
      NONE) ;;
      DESKTOP)
         SECONDARY_DESKTOP_CONNECTOR=$CONNECTOR1
         MONITOR_LAYOUT=SECONDARY_DESKTOP
         SetConfFileParameter SECONDARY_DESKTOP_CONNECTOR $CONNECTOR1
     ;;
esac
}
##################### Aufloesung fuer VDR Bildschirm waehlen #####################
#Was fuer eine Aufloesung soll verwendet werden ?
#RESOLUTION_ARRAY  -> Hier werden die Auflösungen erwartet Format: 1920x1080 50.0Hz
#1 Parameter -> Text der angezeigt wird
#2 Parameter -> Screen_mod Name für Conf File
Screen_Resolution_Checkbox()
{
local NR=0
local TEXT=$1
local SCREEN_MODE=$2
############# Leerstellen entfernen ###############
local RESOLUTION=$(echo ${RESOLUTION_ARRAY[$NR]} | cut -d " " -f1)
RESOLUTION=$RESOLUTION"_"$(echo ${RESOLUTION_ARRAY[$NR]} | cut -d " " -f2)
RESOLUTION=$RESOLUTION"_"$(echo ${RESOLUTION_ARRAY[$NR]} | cut -d " " -f3)


local LIST[$NR]=" Empfohlene-Aufloesung  $RESOLUTION  on "
NR=1

while true
do
 if [ $(echo ${RESOLUTION_ARRAY[$NR]} | grep -c "FINITO") -eq "1" ];then
  break
 fi

############# Leerstellen entfernen ###############
 RESOLUTION=$(echo ${RESOLUTION_ARRAY[$NR]} | cut -d " " -f1)
 RESOLUTION=$RESOLUTION"_"$(echo ${RESOLUTION_ARRAY[$NR]} | cut -d " " -f2)
 RESOLUTION=$RESOLUTION"_"$(echo ${RESOLUTION_ARRAY[$NR]} | cut -d " " -f3)
 LIST[$NR]=" Aufloesung-$NR  $RESOLUTION  off "
 NR=$(($NR+1))
done

OK_CANCEL=1
SEL_RESOLUTION=$(dialog \
     --backtitle "$BACKTITLE" \
     --title "$TITLE" \
     --ok-label " O.K. "\
     --radiolist "\n\
$TEXT" $DIA_BOX_SIZE\
 ${LIST[@]} 3>&1 1>&2 2>&3 3>&- )
OK_CANCEL=$?
clear

case $SEL_RESOLUTION in
      "Empfohlene-Aufloesung")
          RESOLUTION=$(echo ${RESOLUTION_ARRAY[0]} | cut -d " " -f1)
          
          #Prüfen ob Graphtft Display
          if [ $(echo ${RESOLUTION_ARRAY[0]} | grep -c "default") -eq "1" ];then
           SetConfFileParameter $SCREEN_MODE "--mode $RESOLUTION"
          else
           RESOLUTION=$RESOLUTION" --rate "$(echo ${RESOLUTION_ARRAY[0]} | cut -d " " -f2) 
           RESOLUTION=$(echo $RESOLUTION | cut -d 'H' -f1)
           SetConfFileParameter $SCREEN_MODE "--mode $RESOLUTION"
          fi
      ;;
      *)
          NR=0
          while true
          do
           if [ "$SEL_RESOLUTION" == "Aufloesung-$NR" ];then

            RESOLUTION=$(echo ${RESOLUTION_ARRAY[$NR]} | cut -d " " -f1)

            #Prüfen ob Graphtft Display
            if [ $(echo ${RESOLUTION_ARRAY[$NR]} | grep -c "default") -eq "1" ];then
             SetConfFileParameter $SCREEN_MODE "--mode $RESOLUTION"
            else
             RESOLUTION=$RESOLUTION" --rate "$(echo ${RESOLUTION_ARRAY[$NR]} | cut -d " " -f2) 
             RESOLUTION=$(echo $RESOLUTION | cut -d 'H' -f1)
             SetConfFileParameter $SCREEN_MODE "--mode $RESOLUTION"
            fi
            break;
           fi
           NR=$(($NR+1))
          done
     ;;
esac
}

############################ Clone Modus #######################################
Clone_Mode ()
{
#Welche Aufloesung soll fuer den Clone Bildschirm verwendet werden?
 if [ $(echo ${VDR_CLONE_SCREEN[0]} | grep -c "FINITO") -eq "1" ];then
  No_Resolution $VDR_CLONE_CONNECTOR
  SetConfFileParameter VDR_CLONE_SCREEN_MODE "--auto"
 else
  #ARRAY Kopieren
  RESOLUTION_ARRAY=("${VDR_CLONE_SCREEN[@]}")
  TEXT="Bildschirm Aufloesung und Frequenz fuer den Clone Bildschirm ($VDR_CLONE_CONNECTOR) waehlen"
  Screen_Resolution_Checkbox "$TEXT" VDR_CLONE_SCREEN_MODE
  unset RESOLUTION_ARRAY
 
#################### Ermittelte Konfiguration einlesen #########################
. $CONF_FILE
######################## Clone Bildschirm skallieren ? #########################
  RESOLUTION_1=$(echo $VDR_SCREEN_MODE | cut -d' ' -f2)
  RESOLUTION_2=$(echo $VDR_CLONE_SCREEN_MODE | cut -d' ' -f2)

  if [ $RESOLUTION_1 != $RESOLUTION_2 ];then
   dialog --backtitle "$BACKTITLE"\
       --title "$TITLE"\
       --yesno "\n\n\
          Der Clone Bildschirm hat eine andere Aufloesung\n\
                       yes das Bild wird skaliert\n\
               no, Bild wird ohne Skalierung dargestellt\n\
       Mit der Maus kann der sichtbare Bereich verschoben werden." $DIA_BOX2_SIZE

   if [ $? -eq "0" ]; then

    X_VDR_SCREEN=$(echo $RESOLUTION_1 | cut -d'x' -f1)
    Y_VDR_SCREEN=$(echo $RESOLUTION_1 | cut -d'x' -f2)

    X_CLONE_SCREEN=$(echo $RESOLUTION_2 | cut -d'x' -f1)
    Y_CLONE_SCREEN=$(echo $RESOLUTION_2 | cut -d'x' -f2)
    #Freq  
    RATE=$(echo $RESOLUTION_2 | cut -d' ' -f4)
    RATE=$(echo $RATE | cut -d 'H' -f1)

    #Skallierung berechnen
    X_FAKTOR=$(echo "scale=3;$X_VDR_SCREEN/$X_CLONE_SCREEN" | bc )
    Y_FAKTOR=$(echo "scale=3;$Y_VDR_SCREEN/$Y_CLONE_SCREEN" | bc )
    
#    Funktioniert nicht mit allen Treibern gleich, ausgebaut 11.04.14
#    #Testen ob Ziel Bildschirm das gleiche Format hat
#    if [ $X_FAKTOR != $Y_FAKTOR ];then

#     dialog --backtitle "$BACKTITLE"\
#       --title "$TITLE"\
#       --yesno "\n\n\
#             Der Clone Bildschirm hat ein anderes Format\n\
#            yes das Bild wird im passenden Format skaliert\n\
#                  no, es wird auf Vollbild skalliert" $DIA_BOX2_SIZE
#
#     if [ $? -eq "0" ]; then
#      if [ $(echo "$X_FAKTOR>$Y_FAKTOR" | bc) -eq "1" ] ; then
#       Y_FAKTOR=$X_FAKTOR
#      else
#       X_FAKTOR=$Y_FAKTOR
#      fi
#     fi
#    fi

#    # Bild zentrieren
#    CLONE_WIDTH=$(echo "scale=3;$X_VDR_SCREEN/$X_FAKTOR" | bc )
#    #Komma abschneiden
#    CLONE_WIDTH=$(echo $CLONE_WIDTH | cut  -d"." -f1)

    YPOS=0
    XPOS=0

#    if [ $(($X_CLONE_SCREEN-$CLONE_WIDTH)) -gt "0" ]; then
#     XPOS=$(($(($X_CLONE_SCREEN-$CLONE_WIDTH))/2))
#    fi

#    CLONE_HEIGHT=$(echo "scale=3;$Y_VDR_SCREEN/$Y_FAKTOR" | bc )
#    #Komma abschneiden
#    CLONE_HEIGHT=$(echo $CLONE_HEIGHT | cut  -d"." -f1)

#   if [ $(($Y_CLONE_SCREEN-$CLONE_HEIGHT)) -gt "0" ]; then
#     YPOS=$(($(($Y_CLONE_SCREEN-$CLONE_HEIGHT))/2))
#    fi

    $LOGGER "clone screen skalierungsfaktor X:$X_FAKTOR  Y:$Y_FAKTOR "
#   #YPOS negieren
#    YPOS=0 #$((YPOS*-1))
    SetConfFileParameter VDR_CLONE_SCREEN_MODE "$VDR_CLONE_SCREEN_MODE --transform $X_FAKTOR,0,$XPOS,0,$Y_FAKTOR,$YPOS,0,0,1"
   fi
  fi
  clear
 fi
}
###############################################################################
### Welche Aufloesung soll fuer den 2. Desktop Bildschirm verwendet werden? ###
Secondary_Desktop_Mode()
{
 if [ $(echo ${SECONDARY_DESKTOP_SCREEN[0]} | grep -c "FINITO") -eq "1" ];then
  No_Resolution $SECONDARY_DESKTOP_CONNECTOR
  SetConfFileParameter SECONDARY_DESKTOP_SCREEN_MODE "--auto"
 else
  #ARRAY Kopieren
  RESOLUTION_ARRAY=("${SECONDARY_DESKTOP_SCREEN[@]}")
  TEXT="Bildschirm Aufloesung und Frequenz fuer den zweiten Desktop Bildschirm ($SECONDARY_DESKTOP_CONNECTOR) "
  Screen_Resolution_Checkbox "$TEXT" SECONDARY_DESKTOP_SCREEN_MODE
  unset RESOLUTION_ARRAY
 fi
}
###############################################################################
# GRAPHTFT 
Graphtft_Mode()
{
if [ $VDR_GRAPHTFT_CONNECTOR != "none" ];then
 ##Ist die Datei vorhanden?
 if [ -e $GRAPHTFT_XORG_CONF ]; then 
  cat $GRAPHTFT_XORG_CONF | sed -e s/"MONITOR_VDR_SCREEN_CONNECTOR"/"$VDR_SCREEN_CONNECTOR"/g > /tmp/xorg.tmp
  cat /tmp/xorg.tmp | sed -e s/"GRAPHTFT_CONNECTOR"/"$VDR_GRAPHTFT_CONNECTOR"/g > /etc/X11/xorg.conf

  case $XORG_CONF_MOD in
         busid)  SET_NVIDIA_BusID
                 ;;
     no_bus_id)  ;;
  esac
  
  else
   dialog --backtitle "$BACKTITLE" --no-cancel --pause "\n\
    Es wird fuer diese Grafikkarte noch kein Infodisplay / GRAPHTFT-plugin unterstuetzt \n\n\
                            - Weiter - " $DIA_BOX4_SIZE $TIMEOUT
  clear
  exit
 fi
 echo "" >> $APT_GET_LOG
 echo "===> ########################################################################################" >> $APT_GET_LOG
 echo "===> `date`: Install vdr-plugin-graphtft ..." >> $APT_GET_LOG
 debconf-apt-progress --logfile $APT_GET_LOG -- apt-get --yes install vdr-plugin-graphtft
 AptStatus=$?
 echo "#############################################################################################" >> $APT_GET_LOG
 echo "" >> $APT_GET_LOG
 if [ $AptStatus -ne 0 ];then
  dialog --backtitle "$BACKTITLE" --no-cancel --pause "\n\
    GRAPHTFT-plugin kann nicht installiert werden \n\n\
                            - Weiter - " $DIA_BOX4_SIZE $TIMEOUT

  $LOGGER "unable to install GRAPHTFT-plugin"
  clear
  exit
 fi


#DISPLAY Parameter setzen
 FRONTEND_DISPLAY=":0.0"
 SetSysconfig "FRONTEND_DISPLAY" "$FRONTEND_DISPLAY"
 INFO_DISPLAY=":0.1"
 SetSysconfig "INFO_DISPLAY" "$INFO_DISPLAY"


 if [ $(echo ${VDR_GRAPHTFT_CONNECTOR[0]} | grep -c "FINITO") -eq "1" ];then
  No_Resolution $VDR_GRAPHTFT_CONNECTOR
  SetConfFileParameter VDR_GRAPHTFT_SCREEN_MODE "--auto"
 else
  #ARRAY Kopieren
  RESOLUTION_ARRAY=("${VDR_GRAPHTFT_SCREEN[@]}")
  TEXT="Bildschirm Aufloesung fuer Infodisplay waehlen ($VDR_GRAPHTFT_CONNECTOR) "
  Screen_Resolution_Checkbox "$TEXT" VDR_GRAPHTFT_SCREEN_MODE
  unset RESOLUTION_ARRAY
#Conf einlesen
. $CONF_FILE
 RESOLUTION=$(echo $VDR_GRAPHTFT_SCREEN_MODE | cut -d " " -f1-2)
 SetConfFileParameter VDR_GRAPHTFT_SCREEN_MODE $RESOLUTION
#Aufloesung einstellen
#  RESOLUTION=$(echo $VDR_GRAPHTFT_SCREEN_MODE | cut -d " " -f2)
#  XRESOLUTION=$(echo $RESOLUTION | cut -d "x" -f1)
#  YRESOLUTION=$(echo $RESOLUTION | cut -d "x" -f2)
#  SetSetupConf graphtft.Height  $YRESOLUTION
#  SetSetupConf graphtft.Width   $XRESOLUTION
 fi
 SetSysconfig "START_GRAPHTFT"  "auf Display 0.1 (Ausgabe ueber x)"
fi

#############################################################################################
#Konfiguration starten und EDID Files speichern

# X Berechtigung, Key löschen sonst läuft X / lightdm nicht richtig 
rm_xauthority

if [ -e $X_TEST_FILE ];then
 rm $X_TEST_FILE
fi
$LOGGER "startx and save EDID data"
startx  "$SETUP/video-setup/x-monitor-layout-check"  --  $PRIMARY_DISPLAY >/dev/null 2>&1

if [ ! -e $X_TEST_FILE ];then
  dialog --backtitle "$BACKTITLE" --no-cancel --pause "\n\
    Grafikmodus kann nicht gestartet werden \n\n\
                            - Weiter - " $DIA_BOX4_SIZE $TIMEOUT

  $LOGGER "unable to start X"
  clear
  exit
fi

}

#############################################################################################
#DISPLAY Parameter setzen
 FRONTEND_DISPLAY=":0"
 SetSysconfig "FRONTEND_DISPLAY" "$FRONTEND_DISPLAY"

#### Frontend Prüfen
Get_Frontend_Class

if [ $FRONTEND_CLASS == "NON_FRE" ]; then
 WriteStatus easyvdr-config-monitor-layout Monitor_layout_configured
 exit
fi
#FF-Karte?
if [ $FRONTEND_CLASS == "NON_X11" ]; then
 #Manueller Aufruf?
 if [ "$Monitor_layout_configured"  != "true" ];then
  WriteStatus easyvdr-config-monitor-layout Monitor_layout_configured
  exit
 fi
fi

#Terminal merken
VT_KONSOLE_OLD=$(fgconsole)         # aktuell aktives Terminal

PID=$(pgrep "easyvdr-runvdr" )
if [ $? -eq 0 ]; then
 easyvdr-vdr stop;sleep 1
fi

PID=$(pgrep "easyvdr-runfron" )
if [ $? -eq 0 ]; then
 easyvdr-frontend stop;sleep 1
fi

# stop X
if ( check_x_running ) >/dev/null 2>&1 ; then
 easyvdr-desktop stop >/dev/null 2>&1 ; sleep 1
fi

chvt $VT_KONSOLE_OLD               # zurueck zur aufrufenden Konsole


################# Bildschirme ueber das Skript steuern ? ########################

#Testen ob !XORG_CONF_AUTO_MODE="yes" vorhanden ist 
if [  $(grep -c XORG_CONF_AUTO_MODE=\"yes\" /etc/X11/xorg.conf) -eq 0 ] ;then
 dialog --backtitle "$BACKTITLE"\
       --title "$TITLE"\
       --yesno "\n\n\
 xorg.conf wurde geaendert,\n
 diese Funktion ist nur mit der original xorg.conf verwendbar\n
 xorg-conf wiederherstellen?" $DIA_BOX2_SIZE 

 if [ $? -ne "0" ]; then
  SetConfFileParameter VDR_SCREEN_CONNECTOR $VDR_SCREEN_CONNECTOR 
  WriteStatus easyvdr-config-monitor-layout Monitor_layout_configured
  exit
 fi
fi
 clear
 

dialog --backtitle "$BACKTITLE"\
       --title "$TITLE"\
       --yesno "\n\n\
      Fuer eine Automatische Erkennung der Bildschirme ja waehlen.\n\
       Bei Haendischen Aenderungen in der xorg.conf nein waehlen.\n\
           Die Auswahl kann nachtraeglich geaendert werden." $DIA_BOX2_SIZE

RET=$?

#Testen ob Version des Conf File passt
if [ X$VIDEO_SETTINGS_CONF_VERSION != X"0.2" ];then
 #Konfiguration rücksetzen
 cp $SETUP/default_settings/easyvdr-video-settings.default $CONF_FILE
 START_VIDEO_DETAILS="true"
fi

if [ $RET -ne "0" ]; then
 #Bildschirm einstellungen deaktivieren
 VDR_SCREEN_CONNECTOR="none"
 SetConfFileParameter VDR_SCREEN_CONNECTOR $VDR_SCREEN_CONNECTOR
 WriteStatus easyvdr-config-monitor-layout Monitor_layout_configured
 exit
fi
clear


## xorg.conf sichern und default wiederherstellen
if [ -e /etc/X11/xorg.conf ]; then
 mv /etc/X11/xorg.conf /etc/X11/xorg.conf_backup
fi

# default für Erkennung der angeschlossenen Bildschirme
cp $CHECK_CONNECTED_DISPLAY_XORG_CONF /etc/X11/xorg.conf


dialog --backtitle "$BACKTITLE" --msgbox "\n\
           Bitte alle angeschlossenen Bildschirme einschalten\n\n\
                               - Weiter - " $DIA_BOX4_SIZE

clear

########################### Monitore ermitteln ################################

#Sind 2 Grafikkarten vorhanden?
XORG_CONF_MOD="Standard"
#busid          -> Standard mit xorg.conf und bus id
#no_xorg.conf   -> Keine xorg.conf
#no_bus_id      -> Mit xorg.conf, ohne Bus Id

if [ $(lspci | grep VGA | grep -c "Intel") -gt "0" ] && [ $(lspci | grep VGA | grep -c "NVIDIA") -gt "0" ]; then

 dialog --backtitle "$BACKTITLE"\
       --title "$TITLE"\
       --extra-button --extra-label "Keine xorg.conf" --cancel-label "Keine Bus ID" --yesno  "\n\n\
                Es sind mehrere Grafikkarten im System,\n\
                    das kann zu problemen fuehren.\n\
           Mit OK wird die Standard Erkennung durchgeführt.\n\
 Wenn Grafikprobleme auftreten,die beiden anderen Optionen versuchen." $DIA_BOX2_SIZE

 RET=$?
 

 case $RET in
      0) XORG_CONF_MOD="busid"
         cp $DEFAULT_XORG_CONF /etc/X11/xorg.conf
         #Bus ID setzen
         SET_NVIDIA_BusID
         ;;
      1) XORG_CONF_MOD="no_bus_id"
         cp $DEFAULT_XORG_CONF /etc/X11/xorg.conf
         ;;
      3) XORG_CONF_MOD="no_xorg.conf"
         #Minimale xorg.conf verwenden.
         cp $SETUP/default_settings/xorg.conf_default /etc/X11/xorg.conf
         ;;
 esac
 
fi


# X Berechtigung, Key löschen sonst läuft X / lightdm nicht richtig 
if [ -f /home/$STANDARD_DESKTOP_USER/.Xauthority ];then
 rm /home/$STANDARD_DESKTOP_USER/.Xauthority >/dev/null 2>&1
fi

if [ -f /root/.Xauthority ];then
 rm /root/.Xauthority >/dev/null 2>&1
fi


$LOGGER "startx for hardware detection"

if [ -e $X_TEST_FILE ];then
 rm $X_TEST_FILE
fi
startx  "$SETUP/video-setup/x-hardware-detection-check-connected-display"  --  $PRIMARY_DISPLAY >/dev/null 2>&1
if [ ! -e $X_TEST_FILE ];then
  dialog --backtitle "$BACKTITLE" --no-cancel --pause "\n\
    Grafikmodus kann nicht gestartet werden \n\n\
                            - Weiter - " $DIA_BOX4_SIZE $TIMEOUT

  $LOGGER "unable to start X"
  clear
  exit
fi
#################### Ermittelte Konfiguration einlesen ########################
. $CONF_FILE
#sleep 10
######################### xorg.conf wiederherstellen ##########################
 case $XORG_CONF_MOD in
      Standard)  cp $DEFAULT_XORG_CONF /etc/X11/xorg.conf
                 ;;
         busid)  cp $DEFAULT_XORG_CONF /etc/X11/xorg.conf
                 #Bus ID setzen
                 SET_NVIDIA_BusID
                 ;;
     no_bus_id)  cp $DEFAULT_XORG_CONF /etc/X11/xorg.conf
                 ;;
  no_xorg.conf)  #Minimale xorg.conf verwenden.
                 cp $SETUP/default_settings/xorg.conf_default /etc/X11/xorg.conf
                 ;;
 esac

################## Mehr als ein Monitor angeschlossen ? #######################
#single nur ein Monitor
MONITOR_LAYOUT=single
################## Bildschirme den Anschluessen zuordnen #################

VDR_SCREEN_CONNECTOR="none"
VDR_CLONE_CONNECTOR="none"
VDR_GRAPHTFT_CONNECTOR="none"
SECONDARY_DESKTOP_CONNECTOR="none"

#Bei mehr als einem Bildschirm die Zuordnungen abfragen
if ( [ $DISPLAY_CONNECTOR2 != "none" ] ); then
 while ([ $VDR_SCREEN_CONNECTOR == "none" ])
 do
  VDR_Screen_Checkbox
  if ( [ $VDR_SCREEN_CONNECTOR == "none" ] ); then
   dialog --backtitle "$BACKTITLE" --no-cancel --pause "\nUngueltiger Anschluss ...\n\n\
  - Weiter - " $DIA_BOX3_SIZE $TIMEOUT
   clear
  fi
 done
else
#Nur ein Bildschirm
VDR_SCREEN_CONNECTOR=$DISPLAY_CONNECTOR1
fi

#Fragen fuer was der 2 Monitor ist
#Bei mehr als einem Bildschirm die Zuordnungen abfragen
if ( [ $DISPLAY_CONNECTOR2 != "none" ] ); then
 VDR_2_Screen_Connector_Checkbox
fi

SetConfFileParameter MONITOR_LAYOUT $MONITOR_LAYOUT
SetConfFileParameter VDR_SCREEN_CONNECTOR $VDR_SCREEN_CONNECTOR
SetConfFileParameter VDR_CLONE_CONNECTOR $VDR_CLONE_CONNECTOR
SetConfFileParameter VDR_GRAPHTFT_CONNECTOR $VDR_GRAPHTFT_CONNECTOR
SetConfFileParameter SECONDARY_DESKTOP_CONNECTOR $SECONDARY_DESKTOP_CONNECTOR


#Graphtft gewünscht?
if ( [ $VDR_GRAPHTFT_CONNECTOR == "none"  ] );then
 #Graphtft abschalten
 SetSysconfig "START_GRAPHTFT"  "no" 
fi

$LOGGER "VDR display layout: $MONITOR_LAYOUT"
$LOGGER "VDR display connector: $VDR_SCREEN_CONNECTOR"
$LOGGER "Display 2 : $DISPLAY_CONNECTOR2"
$LOGGER "Display 3 : $DISPLAY_CONNECTOR3"
$LOGGER "VDR_CLONE_CONNECTOR : $VDR_CLONE_CONNECTOR"
$LOGGER "VDR_GRAPHTFT_CONNECTOR : $VDR_GRAPHTFT_CONNECTOR"
$LOGGER "SECONDARY_DESKTOP_CONNECTOR : $SECONDARY_DESKTOP_CONNECTOR"

######################## Aufloesung & Freq. ermitteln ###########################
#
dialog --backtitle "$BACKTITLE" --no-cancel --pause "\n\
        Es werden die Daten der erkannten Bildschirme ermittelt \n\n\
                            - Weiter - " $DIA_BOX4_SIZE $TIMEOUT

clear

# X Berechtigung, Key löschen sonst läuft X / lightdm nicht richtig 
if [ -f /home/$STANDARD_DESKTOP_USER/.Xauthority ];then
 rm /home/$STANDARD_DESKTOP_USER/.Xauthority >/dev/null 2>&1
fi

if [ -f /root/.Xauthority ];then
 rm /root/.Xauthority >/dev/null 2>&1
fi


if [ -e $X_TEST_FILE ];then
 rm $X_TEST_FILE
fi

$LOGGER "startx for resolution-check"
startx  "$SETUP/video-setup/x-hardware-detection-check-display-resolution"  --  $PRIMARY_DISPLAY >/dev/null 2>&1
if [ ! -e $X_TEST_FILE ] || [ ! -e $RESOLUTION_FILE ] ;then
  dialog --backtitle "$BACKTITLE" --no-cancel --pause "\n\
    Grafikmodus kann nicht gestartet werden \n\n\
                            - Weiter - " $DIA_BOX4_SIZE $TIMEOUT

  $LOGGER "unable to start X"
  clear
  exit
fi



#sleep 10
#################### Ermittelte Konfiguration einlesen ########################
. $CONF_FILE
. $RESOLUTION_FILE
############################ Auswahl der Aufloesung ############################
#Welche Aufloesung soll verwendet werden?
if [ $(echo ${VDR_SCREEN[0]} | grep -c "FINITO") -eq "1" ];then
  No_Resolution $VDR_SCREEN_CONNECTOR
  SetConfFileParameter VDR_SCREEN_MODE "--auto"
else

 #ARRAY Kopieren
 RESOLUTION_ARRAY=("${VDR_SCREEN[@]}")
 TEXT="Bildschirm Aufloesung und Frequenz fuer den VDR Bildschirm ($VDR_SCREEN_CONNECTOR) waehlen"
 Screen_Resolution_Checkbox "$TEXT" VDR_SCREEN_MODE
 unset RESOLUTION_ARRAY
fi


if [ $VDR_CLONE_CONNECTOR != "none" ];then
 Clone_Mode
fi

if [ $SECONDARY_DESKTOP_CONNECTOR != "none" ];then
 Secondary_Desktop_Mode
fi

if [ $VDR_GRAPHTFT_CONNECTOR != "none" ];then
 Graphtft_Mode
fi
#################### Ermittelte Konfiguration einlesen ########################
. $CONF_FILE
$LOGGER "VDR screen mode: $VDR_SCREEN_MODE"
$LOGGER "VDR clone screen mode: $CLONE_SCREEN_MODE"
$LOGGER "VDR secondary screen mode: $SECONDARY_DESKTOP_SCREEN_MODE"
$LOGGER "VDR GRAPHTFT screen mode: $VDR_GRAPHTFT_SCREEN_MODE"
###############################################################################

######################### Ausgabegerätprüfung deaktivieren?
 dialog --backtitle "$BACKTITLE"\
       --title "$TITLE"\
       --defaultno --yesno "\n\n\
 Die gewaehlten Parameter ohne Pruefung des Ausgabegeraetes aktivieren?\n\
   Bei Problemen mit AV Receiveren kann diese Funktion Probleme lösen,\n\
    es werden die gewaehlten Parameter ohne Ueberpruefung aktiviert.\n\
              Die X Schutzfunktionen sind weiterhin aktiv.\n\
  Es besteht ein Risiko fuer Hardware Schäden bei falschen Paramtern " $DIA_BOX2_SIZE

if [ $? -eq "0" ]; then
 SetSysconfig "CHECK_DISPLAY"  "no"
fi

########################## Fertige Konfiguration testen ######################
#startx  "$SETUP/video-setup/x-hardware-detection-check-vdpau-vaapi"  --  $PRIMARY_DISPLAY


WriteStatus easyvdr-config-monitor-layout Monitor_layout_configured

. $SETUP_STATUS

if [ "$Video_details_configured" == "true" ] ; then
 if [ $START_VIDEO_DETAILS == "true" ] ; then
  $SETUP/easyvdr-config-video-details
 fi
fi

#################### Ermittelte Konfiguration einlesen ########################
#. /etc/vdr/easyvdr/easyvdr-video-settings.conf

#Xorg.conf anpassen
## Ist die Datei vorhanden?
#if [ -e /etc/X11/xorg.easyvdr ]; then 
#  cat /etc/X11/xorg.easyvdr | sed -e s/"MONITOR_VDR_SCREEN_CONNECTOR"/"$MONITOR_VDR_SCREEN_CONNECTOR"/g > /tmp/xorg.conf1
#  cat       /tmp/xorg.conf1 | sed -e s/"MONITOR_VDR_SCREEN_H_SYNC"/"$MONITOR_VDR_SCREEN_H_SYNC"/g >  /tmp/xorg.conf2
#  cat       /tmp/xorg.conf2 | sed -e s/"MONITOR_VDR_SCREEN_V_SYNC"/"$MONITOR_VDR_SCREEN_V_SYNC"/g >  /tmp/xorg.conf3

#  cat  /tmp/xorg.conf3 | sed -e s/"DISPLAY_CONNECTOR2"/"$DISPLAY_CONNECTOR2"/g >                     /tmp/xorg.conf4
#  cat  /tmp/xorg.conf4 | sed -e s/"MONITOR_VDR_SCREEN_H_SYNC_2"/"$MONITOR_VDR_SCREEN_H_SYNC_2"/g >   /tmp/xorg.conf5
#  cat  /tmp/xorg.conf5 | sed -e s/"MONITOR_VDR_SCREEN_V_SYNC_2"/"$MONITOR_VDR_SCREEN_V_SYNC_2"/g >   /etc/X11/xorg.conf
#fi


